### ISSUE TITLE
Unable to deploy common partition 

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-appsvcs-extension#399] opened 2020-12-19 19:37 UTC
### Environment
 * Application Services Version: 3.24.0'
 * BIG-IP 15.1.0.5 Build 0.0.8 Point Release 5

### Summary
When submitting the /Common/Shared declaration with a single pool containing x amount of nodes (serverAddresses) it fails with status 422 and message "Cannot read property 'forEach' of undefined",

This is done as an attempt to try and mitigate: https://github.com/F5Networks/f5-appsvcs-extension/issues/340

I have removed everything in /Common/Shared prior to submitting this declaration, and that went OK, so there are no references from the old bigip gui conf that we are running in parallel (I have also checked bigip.conf files).

All nodes (including pool members) in this f5 device lives in Common (including those that lives in manually managed "f5 gui partitions"). 

Edit: after some more tests and removing lots of the nodes (in the real example I have 180+ nodes but I removed many of them to make the example clearer). Anyway, when I removed the majority of the nodes and only included a few ones (and then only nodes that are _not_ referenced by another as3 declaration (we have 1), then I received the following error instead: "response": "01020066:3: The requested Node (/Common/10.1.108.40%100) already exists in partition Common.",

So I think this one is related to the previous issue I have placed https://github.com/F5Networks/f5-appsvcs-extension/issues/340. Would be great if this would be fixed at the same time (and if so, do you have any estimate when the previous issue might be fixed? :) )

### Steps To Reproduce
1. Submit the following declaration:
```json
{
  "class": "AS3",
  "action": "deploy",
  "persist": true,
  "declaration": {
    "class": "ADC",
    "updateMode": "selective",
    "id": "5aa57f66-1b9b-4c16-ac7c-bf629f557d70",
    "schemaVersion": "3.24.0",
    "Common": {
      "class": "Tenant",
      "enable": true,
      "Shared": {
        "class": "Application",
        "template": "shared",
        "enable": true,
        "all_nodes_pool": {
          "class": "Pool",
          "loadBalancingMode": "round-robin",
          "serviceDownAction": "none",
          "members": [
            {
              "servicePort": 54322,
              "serverAddresses": [
                "10.1.108.40%100",
                "10.10.10.10",
                "10.10.10.10%2",
                "10.10.10.11",
                "10.16.242.9%2"
              ],
              "priorityGroup": 0,
              "shareNodes": true
            }
          ]
        }
      }
    }
  }
}
```

2. Observe the following error response:
```json
results: [
  {
     "message": "Cannot read property 'forEach' of undefined",
     "host": "localhost",
     "tenant": "Common",
     "code": 422
  },
  {
     "message": "Cannot read property 'forEach' of undefined",
     "host": "localhost",
     "tenant": "Common",
     "code": 422
  }
]
```

### Expected Behavior
The /Common/Shared partition to deploy successfully. 

### Actual Behavior
The declaration fails to deploy.

**Comment by dstokesf5** [comment] 2021-01-21 21:41
Following your steps for reproduction I was unable to reproduce the issue. I get the following response to your declaration:
```json
    "results": [
        {
            "code": 200,
            "message": "success",
            "lineCount": 24,
            "host": "localhost",
            "tenant": "Common",
            "runTime": 4470
        },
        {
            "code": 200,
            "message": "no change",
            "host": "localhost",
            "tenant": "Common",
            "runTime": 3324
        }
    ],
```

I suspect you are getting an error because of existing BIG-IP configuration. Can you provide the tmsh configuration of any relevant nodes already on the device?

**Comment by oakh1** [comment] 2021-01-22 17:15
I did some further more extensive checks and I have verified that this happens when there's a node (in **Common**) belonging to an existing "bigip gui created" pool.

This in in other words similar to: https://github.com/F5Networks/f5-appsvcs-extension/issues/340 with the difference that this log message is the result of some kind of internal error rather than a logical error.

To reproduce the error:

1. Create a pool in the GUI with a pool inside common
2. Create an as3 declaration with shareNodes: true and use the same ip address as the one you created in the GUI.
3. See error: "message": "Cannot read property 'forEach' of undefined"

**Comment by dstokesf5** [comment] 2021-01-28 00:09
I was able to reproduce and confirm the bug. I have added it to our internal product backlog as AUTOTOOL-2136. Thank you for reporting the issue.

**Comment by dstokesf5** [comment] 2021-02-25 21:15
It looks like this was resolved while fixing a similar bug. The fix should be available in the 3.27.0 release.

**Comment by dstokesf5** [comment] 2021-04-06 17:57
This issue was resolved in the 3.27.0 release.

**Closed by dstokesf5** 2021-04-06 17:57 UTC
Labels: bug

**Comment by jainvijay1** [comment] 2022-03-29 16:41
> @jainvijay1 it is recommended to deploy in an application tenant. Please review the best practices document https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/best-practices.html#keep-the-number-of-applications-in-one-tenant-to-a-minimum

Agreed, But we have deployed our application in Common Partition only. Is there any way i can use AS3 for automation?

**Comment by mdditt2000** [comment] 2022-03-29 16:56
@jainvijay1 recommend deploying those application to an application partition and avoid common. Use Common for policies, profiles, common nodes etc. AS3 tenants can reference these /Common objects. Here is an example https://support.f5.com/csp/article/K41856551

**Comment by jainvijay1** [comment] 2022-03-29 17:17
> @jainvijay1 recommend deploying those application to an application partition and avoid common. Use Common for policies, profiles, common nodes etc. AS3 tenants can reference these /Common objects. Here is an example https://support.f5.com/csp/article/K41856551

Thanks. I'm able to deploy the Virtual Server with using /Common objects and it's working as expected. Actual problem is when I deployed the VS one time it's works but when try to create second VS it overwrite the first created one. Not sure why this is happening? Please advise.
