### ISSUE TITLE
When POSTed new nodes at dynamic Discovery endpoint - on Bigip having existing nodes under same pool - the newly added nodes were not added to the pool.

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#196] opened 2019-11-19 16:58 UTC
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report
 
##### AS3 BUILD/ VERSION
This issue has been observed on 2 deployments as below.

Build Details :

1) BigIP v 13.1.1 ( Physical , Standalone)
   AS3 v 3.15.0-6

2) BigIPv 14.1.2 ( VE , Standalone)
   AS3 v 3.15.0-6

##### SUMMARY
Dynamic EP attach fails to add new members to existing pool and on VE, BigIP services restarted when new endpoints added to service discovery endpoint on top of existing ones.

##### STEPS TO REPRODUCE
Steps :
1) Created application with dynamic EP mapping. Observed after the Mapping creation, All the EPs were learnt and added properly to the pool on BigIP
2) Added 2 more members to the same Service Discovery Endpoint.
3) However, the for these EPs, nodes got created but they nodes were not added as pool members.

json POSTs for above steps :

1. JSON POST for creating mapping :
```json
{
    "schemaVersion": "3.15.0",
    "class": "ADC",
    "Part_157_10": {
        "App_10": {
            "constants": {
                "serviceCenterEPG": {
                    "web_pool": {
                        "application": "AppProfile",
                        "tenant": "Demo",
                        "epg": "EPG-Internal3"
                    }
                },
                "class": "Constants"
            },
            "web_pool": {
                "class": "Pool",
                "members": [{
                        "serverAddresses": [],
                        "servicePort": 80
                    }, {
                        "addressDiscovery": "event",
                        "servicePort": 1200
                    }
                ],
                "monitors": ["http"]
            },
            "class": "Application",
            "template": "http",
            "serviceMain": {
                "class": "Service_HTTP",
                "pool": "web_pool",
                "virtualAddresses": ["7.7.7.7"]
            }
        },
        "class": "Tenant"
    },
    "id": "42333f76-09c0-4046-bb89-766180e6d225"
}
```

Endpoints discovered at the mapping creation time :

Observed that 6 endpoints present at portgroup were detected and added to Bigip while creating above config.

----------------------------------------------------

Node list present on BigIP after above POST.

        "nodeList": [
            {
                "ip": "12.120.1.2",
                "id": "/Part_157_10/12.120.1.2"
            },
            {
                "ip": "12.120.1.3",
                "id": "/Part_157_10/12.120.1.3"
            },
            {
                "ip": "12.120.1.5",
                "id": "/Part_157_10/12.120.1.5"
            },
            {
                "ip": "12.120.1.4",
                "id": "/Part_157_10/12.120.1.4"
            },
            {
                "ip": "12.120.1.1",
                "id": "/Part_157_10/12.120.1.1"
            },
            {
                "ip": "172.16.100.2",
                "id": "/Part_157_10/172.16.100.2"
            }
            
        ]

2. Used POSTMAN to post below node list to bigIP service discovery endpoint to add 4 more endpoints :  https://<BIGIP MGMT Address>/mgmt/shared/service-discovery/task/~Part_157_10~App_10~web_pool/nodes

 [
                {
                    "ip": "12.120.1.2",
                    "id": "12.120.1.2"
                },
                {
                    "ip": "12.120.1.3",
                    "id": "12.120.1.3"
                },
                {
                    "ip": "12.120.1.5",
                    "id": "12.120.1.5"
                },
                {
                    "ip": "12.120.1.4",
                    "id": "12.120.1.4"
                },
                {
                    "ip": "12.120.1.1",
                    "id": "12.120.1.1"
                },
                {
                    "ip": "172.16.100.2",
                    "id": "172.16.100.2"
                },
				{
                    "ip": "172.16.100.3",
                    "id": "172.16.100.3"
                },
				{
                    "ip": "172.16.100.4",
                    "id": "172.16.100.4"
                },
				{
                    "ip": "172.16.100.5",
                    "id": "172.16.100.5"
                },
				{
                    "ip": "172.16.100.7",
                    "id": "172.16.100.7"
                }
            ]
 
  
-----------

Observations :

1. The nodes were created however they were not added to pool.

2. Observed below logs on BigIP ( restnoded.log )

Tue, 19 Nov 2019 09:32:11 GMT - finest: socket 208 opened
Tue, 19 Nov 2019 09:33:07 GMT - info: [f5-service-discovery: Task.js] Task ~Part_157_10~App_10~web_pool failed: Cannot read property 'replace' of undefined
Tue, 19 Nov 2019 09:33:13 GMT - finest: socket 208 closed

Broadcast message from systemd-journald@ (Tue 2019-11-19 01:33:49 PST):

logger[21821]: Re-starting tmm

2019 Nov 19 01:33:50  logger[21821]: Re-starting tmm

Broadcast message from systemd-journald@ (Tue 2019-11-19 01:33:50 PST):

logger[21830]: Re-starting tmm1

2019 Nov 19 01:33:50  logger[21830]: Re-starting tmm1

Broadcast message from systemd-journald@ (Tue 2019-11-19 01:33:52 PST):

logger[21840]: Re-starting tmm2

2019 Nov 19 01:33:52  logger[21840]: Re-starting tmm2

Broadcast message from systemd-journald@ (Tue 2019-11-19 01:33:53 PST):

logger[21850]: Re-starting tmm3

2019 Nov 19 01:33:53  logger[21850]: Re-starting tmm3

##### EXPECTED RESULTS
The Endpoints added as nodes should have got added under respective pool.

##### ACTUAL RESULTS
Dynamic EP attach failed to add new members to existing pool and - on VE - BigIP services restarted when new endpoints added to service discovery endpoint.

**Comment by dstokesf5** [comment] 2019-11-19 17:36
It really helps us if you describe things in AS3 terms instead of Service Center terms. I am a bit confused about step 1:
>Created application with dynamic EP mapping. Observed after the Mapping creation, All the EPs were learnt and added properly to the pool on BigIP

Are you creating an event driven service discovery pool member and then POSTing nodes to the service discovery nodes endpoint to create this initial pool of 6 nodes? Or are they coming from somewhere else?

**Comment by kedargslab** [comment] 2019-11-19 17:43
You are right. We are creating event driven service discovery pool members and then POSTing nodes to the service discovery nodes endpoint to create the initial pool of 6 nodes .And after that the issue is observed when trying to add new nodes to same pool on bigip. It only created nodes under the bigip partition however they were not added as pool members.

**Comment by dstokesf5** [comment] 2019-11-19 18:34
I was able to reproduce the issue, and I have created internal product backlog item AUTOTOOL-989 to track it. We will try to get this resolved before the 3.16 release.

**Comment by kedargslab** [comment] 2019-12-17 06:22
Has this been fixed in 3.16 as mentioned above?

**Comment by dstokesf5** [comment] 2019-12-17 15:55
Yes, this should be resolved in 3.16.0.

**Comment by dstokesf5** [comment] 2020-01-10 01:05
Closing this issue since 3.16.0 has been released.

**Closed by dstokesf5** 2020-01-10 01:05 UTC
Labels: bug

**Comment by kedargslab** [comment] 2020-03-18 08:32
Found during testing integration with F5 ACI ServiceCenter
