### ISSUE TITLE
AS3 3.23 does not honor mask of Service_Address when creating VS

### ISSUE THREAD

**Issue by jussisjostrom** [F5Networks/f5-appsvcs-extension#365] opened 2020-10-21 08:13 UTC
### Environment
 * Application Services Version: 3.23
 * BIG-IP Version: 14.1.2.8

### Summary
Virtual servers are created with mask 255.255.255.255, even if the virtualAddress property refers to Service_Address with /0 mask.
This is reproducable and seems to have been introduced in 3.23 because I've used the same declaration with previous versions of AS3 and the vs have been created with correct mask.

The issue seriously affects the ability to create forwarding VS using AS3.

### Steps To Reproduce

1. Submit the following declaration for ServiceAddress in /Common/Shared:
```json
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "destAny_ipv4": {
                    "class": "Service_Address",
                    "arpEnabled": false,
                    "icmpEcho": "disable",
                    "routeAdvertisement": "disable",
                    "virtualAddress": "0.0.0.0/0"
                },
```
Then, in the tenants declaration, use this ServiceAddress definition for the virtualAddress property:
```json
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
...
        "APN01": {
            "class": "Tenant",
            "defaultRouteDomain": 0,
            "APN": {
                "class": "Application",
                "label": "APN01",
                "template": "generic",
...
                "vs_out_nat44_udp": {
                    "class": "Service_L4",
                    "label": "VS for default UDP NAT44",
                    "layer4": "udp",
                    "translateServerAddress": false,
                    "translateServerPort": false,
                    "virtualAddresses": [
                        [{ "bigip": "/Common/Shared/destAny_ipv4" }, "0.0.0.0/0" ]
                    ],
                    "allowVlans": [
                        { "bigip":"/Common/idag" }
                    ],
                    "virtualPort": 0,
                    "profileL4": { "use": "fastL4udp" },
                    "snat": "none",
                    "policyFirewallEnforced": {"use":"FW_POL_APN01_IPv4_knownsubs"},
                    "policyNAT": {"use": "cgnat_policy"},
                    "persistenceMethods": []
                },
```
In tmsh, the virtual-address is created correctly:
```
    ltm virtual-address Shared/destAny_ipv4 {
        **address any**
        arp disabled
        icmp-echo disabled
        inherited-traffic-group true
        **mask any**
        traffic-group traffic-group-1
    }
```

But... In the virtual server, the mask of the virtual-address is not honored:
```
ltm virtual /APN01/APN/vs_out_nat44_udp {
    creation-time 2020-10-21:00:43:27
    description APN
    **destination Shared/destAny_ipv4:any**
    fw-enforced-policy /APN01/APN/FW_POL_APN01_IPv4_knownsubs
    ip-protocol udp
    last-modified-time 2020-10-21:00:43:27
    **mask 255.255.255.255**
    partition APN01
    profiles {
        /APN01/APN/fastL4udp { }
    }
    security-nat-policy {
        policy /APN01/APN/cgnat_policy
    }
    source 0.0.0.0/0
    translate-address disabled
    translate-port disabled
    vlans {
        idag
    }
    vlans-enabled
    vs-index 234
}```

### Expected Behavior
Expected behaviour would be that the mask of the virtual server is the mask of the virtual-address object referred to.

### Actual Behavior
Mask is incorrectly 255.255.255.255 for vs, while mask for virtual address is any, ie 0.0.0.0.

**Comment by jussisjostrom** [comment] 2020-10-21 14:43
It seems that the issue is that when you use pointers (tested with "bigip", unknown if same applies for "use") in the virtualAddress property for Service, then the vs created is assigned a mask of 255.255.255.255 (IPv4).
I see same issue, when trying to create a forwarding VS for IPv6, and using a virtualAddress like this:
`
                "vs_out_fwd6_tcp": {
                    "class": "Service_L4",
                    "label": "VS for default TCP fwd IPv6",
                    "layer4": "tcp",
                    "translateServerAddress": false,
                    "translateServerPort": false,
                    "virtualAddresses": [
                        [{"bigip":"/Common/Shared/destAny_ipv6"}, "fc00:1::/32"]
                    ],
                    "allowVlans": [
                        { "bigip":"/Common/idag" }
                    ],
                    "virtualPort": 0,
                    "profileL4": { "use": "fastL4tcp" },
                    "snat": "none",
                    "persistenceMethods": []
                },
`
Then, the AS3 post results in the error message:
`
0107028f:3: The destination (::) address and mask (255.255.255.255) for virtual server (/APN01/APN/vs_out_fwd6_tcp) must be be the same type (IPv4 or IPv6)
`
If the virtualAddress for above Service is specified like this:
`
                    "virtualAddresses": [
                        ["fc00:0::/32", "fc00:1::/32"]
                    ],
`
the POST is succesfull and vs is created fine, but virtual-address has arp and icmp-echo enabled, which is not right. Therefore, the reference to an already created ServiceAddress object must be used, as documented...

**Comment by wncocz** [comment] 2020-10-21 14:46
This sounds like my #339

**Comment by dstokesf5** [comment] 2020-10-22 22:33
Confirmed that this looks like a duplicate of #339. Closing this one.

**Closed by dstokesf5** 2020-10-22 22:33 UTC
Labels: bug, untriaged
