### ISSUE TITLE
shareNodes notworking for FQDN nodes

### ISSUE THREAD

**Issue by DahlPatric** [F5Networks/f5-appsvcs-extension#796] opened 2024-01-31 10:12 UTC
### Environment
 * Application Services Version: 3.46.2
 * BIG-IP Version: 14.1

### Summary
Issues when trying to use SharedNodes with FQDN nodes what we believe causing the issue.
 
### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "servicePort": 1525,
    "hostname": "flosvl1014.flo.volvocars.net",
    "addressDiscovery": "fqdn",
    "shareNodes": true
}
```

2. Observe the following error response:
```json
"errors": [
        "/Tenant/app-MyApp/app-MyPool/members: pool member /Tenant/app-MyApp/app-MyPool/members/0 fqdn hostname server1.locl conflicts with bigip fqdn node /app-MyPool/server1.locl"
    ],
```

When we using ShardNodes in declaration we does not either see them be installed in /Common/Shared.

### Actual Behavior
SharedNodes seam not be installed in ShardNodes folder initially.
When installing another declaration with same nodes causing error,

**Comment by npmaslow** [comment] 2024-02-02 16:40
This is also reproducible by F5 PS Internally and is being encountered by a customer. Please advise on resolution.

**Comment by sunitharonan** [comment] 2024-02-21 18:06
Please reach out to us at automation_toolchain_pm@f5.com in order for us to prioritize. Thanks.

**Comment by MicSkr** [comment] 2024-04-15 20:02
Also having this issue. Reached out to your email.

**Comment by mdditt2000** [comment] 2024-04-16 17:46
Jira issue is AUTOTOOL-4178. I only have one customer name for this Jira. Would help prioritize if i had both. Please reach out at the email address above. Spring planning is tomorrow.

**Comment by MicSkr** [comment] 2024-04-16 20:33
Reached out. Thanks @mdditt2000 !

**Comment by MicSkr** [comment] 2024-05-08 14:49
Is there an update on when this will be released? This is holding back FQDN configurations and making it difficult for operators to perceive devices by FQDN.

**Comment by sunitharonan** [comment] 2024-06-26 17:21
Reached out to customer through email to gather more information. Closing as we are unable to reproduce.

**Closed by sunitharonan** 2024-06-26 17:21 UTC
Labels: bug
