### ISSUE TITLE
Error "requested Pool Member was not found" observed on removing dynamic service discovery entry from application

### ISSUE THREAD

**Issue by manukanade** [F5Networks/f5-appsvcs-extension#185] opened 2019-11-11 08:24 UTC
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION
f5-appsvcs-3.15.0-6.noarch

##### BIGIP VERSION
BIG-IP 13.1.1.3 Build 0.0.1 Point Release 3

##### SUMMARY
Submit an AS3 application with dynamic discovery enabled. A few nodes get dynamically discovered and added to the pool of that application. Remove the dynamic discovery entry from the application and re-submit the declaration. At this time an error is seen: 

##### STEPS TO REPRODUCE
1. Posted declaration 
```
{"Sample_40": {"optimisticLockKey": "hZYQaSdS0y2lnnp/02ve+dOG5dRmzuMRVuqW5c7np4M=", "A2": {"constants": {"serviceCenterEPG": {}, "class": "Constants"}, "web_pool": {"class": "Pool", "members": [{"serverAddresses": [], "servicePort": 80}, {"addressDiscovery": "event", "servicePort": 9090}], "monitors": ["http"]}, "class": "Application", "template": "http", "serviceMain": {"class": "Service_HTTP", "pool": "web_pool", "virtualAddresses": ["10.10.10.10"]}}, "class": "Tenant"}, "schemaVersion": "3.0.0", "class": "ADC", "id": "fbccbe09-a205-4375-a6e1-e4158ec42fed"}
```
2. After this there were endpoints observed on https://<BIG-IP IP>/mgmt/shared/service-discovery/task/~Sample_40~A2~web_pool
3. Re-submitted the app, by removing dynamic discovery. POST of declaration
```
{"Sample_40": {"optimisticLockKey": "w6LqPDavDt+TVoEmojZOUL3wjWuKvN9yIquzyFdnG9U=", "A2": {"constants": {"serviceCenterEPG": {}, "class": "Constants"}, "web_pool": {"class": "Pool", "members": [{"serverAddresses": [], "servicePort": 80}], "monitors": ["http"]}, "class": "Application", "template": "http", "serviceMain": {"class": "Service_HTTP", "pool": "web_pool", "virtualAddresses": ["10.10.10.10"]}}, "class": "Tenant"}, "schemaVersion": "3.0.0", "class": "ADC", "id": "e6654325-13c9-46f4-8152-a2f66b63cf61"}
```

##### EXPECTED RESULTS
Expected the declaration in step 3 to remove the dynamically discovered nodes from the pool

##### ACTUAL RESULTS
Got error from BIG-IP, and the dynamic discovery removal {"addressDiscovery": "event", "servicePort": 9090} from declaration JSON did not work, and also dynamically discovered nodes did not get removed from the pool

```
01020036:3: The requested Pool Member (/Sample_40/A2/web_pool /Common/192.168.10.11 9090) was not found.
```

**Comment by dstokesf5** [comment] 2019-11-12 23:52
Thank you for reporting this issue. I have added it to our internal product backlog as AUTOTOOL-963.

**Comment by dstokesf5** [comment] 2019-11-12 23:55
Closing this issue as a duplicate of #162

**Closed by dstokesf5** 2019-11-12 23:55 UTC
Labels: bug

**Comment by kedargslab** [comment] 2020-03-18 08:29
Found during testing integration with F5 ACI ServiceCenter
