### ISSUE TITLE
Pool_Member remark being ignored

### ISSUE THREAD

**Issue by kenfng** [F5Networks/f5-appsvcs-extension#498] opened 2021-08-27 00:25 UTC
### Environment
 * Application Services Version:
 * BIG-IP Version: 15.1.3 build 0.0.11

### Summary
Please also include information about the reproducibility and the severity/impact of the issue.

Node attribute remark is always ignored, and does not cause the description field of the node to be populated.
Node name also remains the IP address when hostname attribute is used (unless traffic type is set to FQDN) as per:
https://github.com/F5Networks/f5-appsvcs-extension/issues/161
and/or
AUTOTOOL-1146

So there is no way to provide node metadata (hostname) to GUI based operators.

Can reproduce: Always

Schema version: 3.30.0

### Steps To Reproduce
Steps to reproduce the behavior (in existing partition):
1. Submit the following declaration (PATCH):
```json
{
    "path": "/Partition/Appname",
    "op": "add",
    "value": {
        "class": "Application",
        "SWIMMING-POOL": {
            "class": "pool",
            "members": [
              {
                "servicePort": "443",
                "remark": "name or description of host",
                "serverAddresses": ["192.0.2.0"]
              }
           ]
        }
    }
}
```

2. Observe the following successful response:
```json
{
    "code": 200,
    "message": "success",
    "host": "localhost",
    "tenant": "Partition",
    "runTime": 1244
}
```

### Expected Behavior
A clear and concise description of what you expected to happen:

list ltm node /Partition/* shows the node description field of "name or description of host":

# list ltm node /Partition/*
ltm node /Partition/192.0.2.0 {
    address 192.0.2.0
    description "name or description of host"
    partition Partition
}

### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.
# list ltm node /Partition/*
ltm node /Partition/192.0.2.0 {
    address 192.0.2.0
    partition Partition
}

**Comment by dstokesf5** [comment] 2021-08-31 18:54
The Pool_Member.remark property is properly updating the description of the pool members. It is not intended to update the description of the individual nodes.

Since the remark property is working correctly, I am closing this issue as a duplicate of #161.

**Closed by dstokesf5** 2021-08-31 18:54 UTC
Labels: bug, untriaged
