### ISSUE TITLE
Add support for monitorType external in GSLB_Monitor

### ISSUE THREAD

**Issue by DaanOlbrechts** [F5Networks/f5-appsvcs-extension#259] opened 2020-04-17 16:24 UTC
### Is your feature request related to a problem? Please describe.
To enable HTTPS SNI-enabled healthchecks for AS3 GSLB pools I want to use the "external" monitor type for GSLB monitors but this option does not exist.

### Describe the solution you'd like
Add monitorType external for GSLB_Monitor, similar to how the LTM "Monitor" has a more specific "Monitor_External".

**Comment by dstokesf5** [comment] 2020-04-23 16:02
Closing as duplicate of #160.

**Comment by dstokesf5** [comment] 2020-04-23 16:04
Actually, keeping this open. I misunderstood the request. This is actually to create an external GSLB monitor with AS3 instead of just referencing one, right?

**Comment by DaanOlbrechts** [comment] 2020-04-24 09:39
Exactly!

**Comment by dstokesf5** [comment] 2020-05-12 15:41
Thank you for your feedback. I have added this to our internal product backlog as AUTOTOOL-1571.

**Comment by dstokesf5** [comment] 2021-08-06 20:22
This issue has been resolved with the 3.30.0 release of AS3.

**Closed by dstokesf5** 2021-08-06 20:22 UTC
Labels: enhancement
