### ISSUE TITLE
Can't post to Common

### ISSUE THREAD

**Issue by canad1an** [F5Networks/f5-appsvcs-extension#27] opened 2018-08-21 15:11 UTC
##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION
f5-appsvcs-3.3.0-6.noarch

##### BIGIP VERSION
12.1.3.3

##### SUMMARY

```
{
	"status": 422,
	"message": "declaration is invalid",
	"errors": [
		"/Common: should NOT have additional properties"
	],
	"code": 422,
	"declarationFullId": ""
}
```

##### STEPS TO REPRODUCE

```
 {
     "class": "AS3",
     "action": "deploy",
     "persist": true,
     "declaration": {
         "class": "ADC",
         "schemaVersion": "3.0.0",
         "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98122ab915d",
         "label": "Sample 1",
         "remark": "Simple HTTP Service with Round-Robin Load Balancing",
         "Common": {
             "A1": {
                 "class": "Application",
                 "template": "http",
                 "testervip": {
                     "class": "Service_HTTP",
                     "virtualAddresses": [
                         "10.0.1.10"
                     ],
                     "pool": "testerpool"
                 },
                 "testerpool": {
                     "class": "Pool",
                     "monitors": [
                         "http"
                     ],
                     "members": [
                         {
                             "servicePort": 80,
                             "serverAddresses": [
                                 "192.0.1.10",
                                 "192.0.1.11"
                             ]
                         }
                     ]
                 }
             }
         }
     }
 }
```

##### EXPECTED RESULTS
200

##### ACTUAL RESULTS

```
422
```

**Comment by jmcalalang** [comment] 2018-08-21 15:20
Hey @canad1an,

[AS3 does not write to Common as a partition](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/userguide/faq.html?highlight=common%20partition):

Why doesn’t AS3 write to the Common partition?

- AS3cdoes not write to the Common partition to ensure there is no impact to an existing device configuration where both AS3 and legacy configuration methods are being used

- While use of separate partitions may be new behavior for some users, F5 has designed AS3 in this manner in order to deliver the safest possible deployment mechanism on BIG-IP

- The use of separate partitions also prevents possible naming collisions and maintains a logical object hierarchy that allows AS3 to deliver stable transactions (atomicity) and idempotency

There are some object however you can reference from Common, I'd recommend looking over some of the example declarations which will have this

**Comment by canad1an** [comment] 2018-08-21 15:38
Thank you. I should have read that doc first.
Can we request this as a feature in future releases?
Thanks!

**Comment by mdditt2000** [comment] 2018-08-21 16:37
Hi @canad1an 

Today we have no plans for AS3 to write to the common partition. However AS3 can reference profiles/policies from common. My recommendation would be to create a "AS3" partition for the services.

**Comment by canad1an** [comment] 2018-08-21 18:59
Ok so we might be able to workaround the common issue.

The next thing i'm seeing is that looks like the vips all have to be named "serviceMain"
Is that the case or can I add a property like "name"

```
					 "A3": {
                 "class": "Application",
                 "template": "http",
                 "Tester1": {
                     "class": "Service_HTTP",
                     "virtualAddresses": [
                         "10.0.1.13"
                     ],
                     "pool": "web_pool3"
                 },
                 "web_pool3": {
                     "class": "Pool",
                     "monitors": [
                         "http"
                     ],
                     "members": [
                         {
                             "servicePort": 80,
                             "serverAddresses": [
                                 "192.0.1.10",
                                 "192.0.1.11"
                             ]
                         }
                     ]
                 }
             }
```

```
{
	"status": 422,
	"message": "declaration is invalid",
	"errors": [
		"/Sample_01/A3: should have required property 'serviceMain'"
	],
	"code": 422,
	"declarationFullId": ""
}
```

**Comment by canad1an** [comment] 2018-08-24 17:49
Ok thanks for the response Mark!

**Comment by 0xHiteshPatel** [comment] 2018-08-27 16:55
Closing this issue since original opener indicated provided answer worked.

**Closed by 0xHiteshPatel** 2018-08-27 16:55 UTC

**Comment by billchurch** [comment] 2019-03-07 14:46
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/faq.html?highlight=ServiceMain

> Do all of my application services need to be named “ServiceMain”?
> 
> No, if you want to name your service something other than serviceMain, use “template:”generic” in the application service of your declaration. You can still use the class property in the application service to specify Service_HTTP or Service_TCP for example, but for each application service in a tenant that uses one of the templates (http, https, tcp, udp, l4), you must use the name serviceMain for your application service. See Example 20 in the AS3 documentation for an illustrative declaration.
