### ISSUE TITLE
The ability to attach a VDI profile

### ISSUE THREAD

**Issue by yahshun** [F5Networks/f5-appsvcs-extension#245] opened 2020-03-27 11:49 UTC
### Is your feature request related to a problem? Please describe.
With the introduction of APM policy imports I would like the ability to automate the deployment of my RDP gateways.  To Deploy the RDP gateway solution additional profiles are required.  Today AS3 supports the attachment of a rewrite and connectivity to the virtual server.  However, I do not see anywhere in the schema the ability to attach a VDI profile.   

### Describe the solution you'd like
AS3 needs the ability to attach a VDI profile to a virtual server.

### Describe alternatives you've considered
My first thought was using icontrolREST to attach the VDI profile after AS3 attached he policy.  However, there is a dependency and the AS3 declaration fails since the VDI profile doesn't exist on the virtual server.

**Comment by dstokesf5** [comment] 2020-03-31 15:38
Closing as duplicate of #153. Since we have multiple people asking for this, I am bumping the priority of AUTOTOOL-1053.

**Closed by dstokesf5** 2020-03-31 15:38 UTC
Labels: enhancement, untriaged
