### ISSUE TITLE
input validation for tenant names

### ISSUE THREAD

**Issue by vbojko** [F5Networks/f5-appsvcs-extension#247] opened 2020-03-31 19:06 UTC
### Environment
 * Application Services Version: 3.18
 * BIG-IP Version: 13.1.4 build 04

### Summary

I can declare a tenant with a dot or underscore in the name.
BIG-IP will accept the tenant and data traffic will pass through BIG-IP.
After the tenant creation, AS3 is not able to show tenant config with
GET:  https://{{bigip_mgmt}}/mgmt/shared/appsvcs/declare/myapp_sometingedg-20
or delete the tenant with
DELETE https://{{bigip_mgmt}}/mgmt/shared/appsvcs/declare/myapp_sometingedg-20

The response for both GET and DELETE is:
{
    "code": 400,
    "message": "invalid Tenant name \"myapp_sometingedg-20\""
}

### Steps To Reproduce
1. Submit the following declaration:
```json
{
"$schema":"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json", 
     "class": "AS3", 
     "action": "deploy", 
     "persist": true, 
     "declaration": { 
         "class": "ADC", 
         "schemaVersion": "3.18.0", 
         "id": "myid", 
         "label": "example", 
         "remark": "This is a description for the AS3 declaration", 
         "myapp_sometingedg-20": { 
             "class": "Tenant", 
             "myapp_sometingedg-20": { 
                 "class": "Application", 
                 "template": "https", 
                 "serviceMain": { 
                     "class": "Service_HTTPS", 
                     "virtualAddresses": [ 
                         "1.1.1.14" 
                     ], 
                     "serverTLS": "vs_ProfileClientSSL", 
                     "clientTLS": "vs__ProfileServerSSL", 
                     "persistenceMethods": [ 
                        "cookie" 
                     ], 
                     "snat": "auto", 
                     "pool": "pool__Pool", 
                     "profileTCP": { 
                         "bigip": "/Common/tcp" 
                     }, 
                     "profileMultiplex": { 
                         "use": "ONECONNECT" 
                     } 
                 }, 
                 "vs_ProfileClientSSL": { 
                     "class": "TLS_Server", 
                     "certificates": [ 
                         { 
                             "certificate": "tlsserver_local_cert" 
                         } 
                     ], 
                     "ciphers": "DEFAULT:!TLSv1:!RC4-SHA:!3DES:!DHE" 
                 }, 
                 "vs__ProfileServerSSL": { 
                 "class": "TLS_Client", 
                 "validateCertificate": false 
                 }, 
                 "tlsserver_local_cert": { 
                    "class": "Certificate", 
			        "certificate": {"bigip":"/Common/default.crt"}, 
        			"privateKey": {"bigip":"/Common/default.key"} 
                 }, 
                 "pool__Pool": { 
                     "class": "Pool", 
                     "members": [ 
						{ "serverAddresses":[ "10.10.10.10" ], "servicePort":443, 
							"connectionLimit":0, 
							"priorityGroup":0, 
							"ratio":1, 
							"adminState":"enable"},
						{ "serverAddresses":[ "10.10.10.11" ], "servicePort":443, 
							"connectionLimit":0, 
							"priorityGroup":0, 
							"ratio":1, 
							"adminState":"enable"}    
 
                    ], 
                     "loadBalancingMode": "round-robin", 
                     "monitors": [ 
                        "http"
                     ] 
                }, 
                 "ONECONNECT": { 
                     "class": "Multiplex_Profile", 
                     "maxConnections": 354900 
                 } 
             } 
         } 
     } 
 } 
```

2. Observe the following error response:
```json
{
    "code": 400,
    "message": "invalid Tenant name \"myapp_sometingedg-20\""
}
```

### Expected Behavior
The AS3 input validation should throw an error stating that the tenant name does not follow the guidelines

### Actual Behavior
AS3 accepts the declaration and creates tenant with dots or dashes in tenant name

**Comment by writemike** [comment] 2020-04-08 13:17
Just wanted to clarify that "AS3 3.17.0 and later allows dots and hyphens in Tenant and Application names."

Source: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/declaration-purpose-function.html#naming-ref

As I understand it the fix will be made to allow dots and hyphens in Tenant Names for GET and DELETE requests, correct?

**Comment by dstokesf5** [comment] 2020-04-08 14:27
@writemike Not being able to DELETE or GET tenants with dots or hyphens was an oversight when we added support for those characters in tenant names. The 3.19.0 release will correct that.

**Comment by hedrickbt** [comment] 2020-04-28 21:10
Any idea when v3.19.0 will be released?

I first started on AS3 with 3.18 and have been focused on creating declarations.  As a result, my naming pattern do not support GET or DELETE due to dashes.  I need to know if I should change my naming patterns or if a solution will be available in the near term.

**Comment by dstokesf5** [comment] 2020-04-28 21:33
v3.19.0 was released last week: https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.19.0

**Comment by hedrickbt** [comment] 2020-04-28 21:48
> v3.19.0 was released last week: https://github.com/F5Networks/f5-appsvcs-extension/releases/tag/v3.19.0


Thanks @dstokesf5 !  Should this issue be marked closed?

**Comment by dstokesf5** [comment] 2020-04-28 22:35
Yup.

**Closed by dstokesf5** 2020-04-28 22:35 UTC
Labels: bug

**Comment by hedrickbt** [comment] 2020-04-29 18:40
Confirmed to be working.

Failed in v3.18, working in v3.19.
DELETE /mgmt/shared/appsvcs/declare/env-appname

Thanks!
