### ISSUE TITLE
Policy_Action_Log 

### ISSUE THREAD

**Issue by grovesgroves** [F5Networks/f5-appsvcs-extension#538] opened 2021-12-21 12:11 UTC
### Is your feature request related to a problem? Please describe.
When creating configuration via tmsh commands Vs. AS3, we have noticed that there an inconsistencies with the same configuration depending on the deployment method. 

### Describe the solution you'd like
We need Policy_Action_Log 

### Additional context

We would also need this work from 'http proxy request event'

https://github.com/F5Networks/f5-appsvcs-extension/issues/131

**Comment by dstokesf5** [comment] 2022-01-11 22:14
Closing as a duplicate of #131. I have noted your need for the proxy request event in our internal backlog item.

**Closed by dstokesf5** 2022-01-11 22:14 UTC
Labels: enhancement, untriaged
