### ISSUE TITLE
Being able to add "not" to Policy Endpoint (LTM policy) condition

### ISSUE THREAD

**Issue by Eken92** [F5Networks/f5-appsvcs-extension#205] opened 2019-12-28 12:32 UTC
### Is your feature request related to a problem? Please describe.
Using the latest as3 version (3.16) it seems like there's no possibility to create an endpoint policy condition which has a "negation" in it, for example, URI path is not /illegalpath/.

### Describe the solution you'd like
Just as it's possible while configuring LTM policies in the GUI, we would like to have the possibility to add a "not" clause to the condition.

### Describe alternatives you've considered
Setting up every single allowed path, but that's not doable in some cases where we need this functionality.

### Additional context
Maybe I am missing something and this is already possible using as3, but this is what I mean:
![image](https://user-images.githubusercontent.com/11943081/71543696-43e23780-2976-11ea-91a8-aad3f9fafa83.png)

**Comment by dstokesf5** [comment] 2020-01-02 17:39
Closing as duplicate of #151

**Closed by dstokesf5** 2020-01-02 17:39 UTC
Labels: enhancement, untriaged
