### ISSUE TITLE
as3 creates partial configuration when there are race conditions for objects referenced in /Common/Shared

### ISSUE THREAD

**Issue by vinnie357** [F5Networks/f5-appsvcs-extension#396] opened 2020-12-16 21:12 UTC
### Environment
 * Application Services Version: 3.22.1
 * BIG-IP Version:  azure 14.1.202000

### Summary
as3 creates partial configuration when there are race conditions for objects referenced in /Common/Shared.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
    "class":"AS3",
    "action":"deploy",
    "persist":true,
    "declaration": { 
        "class": "ADC",
        "schemaVersion": "3.12.0",
        "id": "05faeb52-4c1b-9fa3-73be-ecd770a57df0",
        "label": "scca baseline",
        "remark": "scca baseline 3.12.0",
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "fwLogDestinationSyslog": {
                    "class": "Log_Destination",
                    "type": "remote-syslog",
                    "remoteHighSpeedLog": {
                        "use": "fwLogDestinationHsl"
                    },
                    "format": "rfc5424"
                },
                "fwLogDestinationHsl": {
                    "class": "Log_Destination",
                    "type": "remote-high-speed-log",
                    "protocol": "tcp",
                    "pool": {
                        "use": "hsl_pool"
                    }
                },
                "hsl_pool": {
                    "class": "Pool",
                    "members": [
                        {
                            "serverAddresses": [
                                "10.90.10.101"
                            ],
                            "enable": true,
                            "servicePort": 514
                        }
                    ],
                    "monitors": [
                        {
                            "bigip": "/Common/udp"
                        }
                    ]
                },
                "fwLogPublisher": {
                    "class": "Log_Publisher",
                    "destinations": [
                        {
                            "use": "fwLogDestinationSyslog"
                        }
                    ]
                },
                "fwSecurityLogProfile": {
                    "class": "Security_Log_Profile",
                    "network": {
                        "publisher": {
                            "use": "fwLogPublisher"
                        },
                        "storageFormat": {
                            "fields": [
                                "action",
                                "dest-ip",
                                "dest-port",
                                "src-ip",
                                "src-port"
                            ]
                        },
                        "logTranslationFields": true,
                        "logTcpEvents": true,
                        "logRuleMatchRejects": true,
                        "logTcpErrors": true,
                        "logIpErrors": true,
                        "logRuleMatchDrops": true,
                        "logRuleMatchAccepts": true
                    },
                    "application": {
                        "facility": "local3",
                        "storageFilter": {
                            "requestType": "illegal-including-staged-signatures",
                            "responseCodes": [
                                "404",
                                "201"
                            ],
                            "protocols": [
                                "http"
                            ],
                            "httpMethods": [
                                "PATCH",
                                "DELETE"
                            ],
                            "requestContains": {
                                "searchIn": "search-in-request",
                                "value": "The new value"
                            },
                            "loginResults": [
                                "login-result-unknown"
                            ]
                        },
                        "storageFormat": {
                            "fields": [
                                "attack_type",
                                "avr_id",
                                "headers",
                                "is_truncated"
                            ],
                            "delimiter": "."
                        },
                        "localStorage": false,
                        "maxEntryLength": "10k",
                        "protocol": "udp",
                        "remoteStorage": "remote",
                        "reportAnomaliesEnabled": true,
                        "servers": [
                            {
                                "address": "10.90.10.101",
                                "port": "514"
                            }
                        ]
                    },
                    "dosApplication": {
                        "remotePublisher": {
                            "use": "fwLogPublisher"
                        }
                    },
                    "dosNetwork": {
                        "publisher": {
                            "use": "fwLogPublisher"
                        }
                    }
                },
                "example_response": {
                    "class": "iRule",
                    "iRule": "when HTTP_REQUEST {\n    HTTP::respond 200 content {\n        <html>\n        <head>\n        <title>Health Check</title>\n        </head>\n        <body>\n        System is online.\n        </body>\n        </html>\n        }\n}"
                },
                "sccaBaselineWAFPolicy":{
                    "class": "WAF_Policy",
                    "url": "https://raw.githubusercontent.com/f5devcentral/f5-asm-policy-templates/master/owasp_ready_template/owasp-auto-tune-v1.1.xml",
                    "ignoreChanges": false,
                "enforcementMode": "transparent"
                },
                "certificate_default": {
                    "class": "Certificate",
                    "certificate": {
                        "bigip": "/Common/default.crt"
                    },
                    "privateKey": {
                        "bigip": "/Common/default.key"
                    }
                },
                "sccaBaselineClientSSL": {
                    "certificates": [
                        {
                            "certificate": "certificate_default"
                        }
                    ],
                    "ciphers": "HIGH",
                    "class": "TLS_Server"
                },
                "sccaBaselineAFMRuleList":{
                    "class": "Firewall_Rule_List",
                    "rules": [
                        {
                            "action": "accept",
                            "name": "allow_all",
                            "protocol": "any"
                        }
                    ]
                },
                "sccaBaselineAFMPolicy": {
                    "class": "Firewall_Policy",
                    "rules": [
                        {
                            "action": "accept",
                            "loggingEnabled": true,
                            "name": "allow_all",
                            "protocol": "any"
                        },
                        {
                            "action": "accept",
                            "loggingEnabled": true,
                            "name": "deny_all",
                            "protocol": "any"
                        }
                    ]
                    
                },
                "sccaBaselineAFMPolicyHTTP": {
                    "class": "Firewall_Policy",
                    "rules": [
                        {
                            "action": "accept",
                            "loggingEnabled": true,
                            "name": "allow_all",
                            "protocol": "any"
                        },
                        {
                            "action": "accept",
                            "loggingEnabled": true,
                            "name": "deny_all",
                            "protocol": "any"
                        }
                    ]
                    
                }
            }
        },
        "transit": {
            "class": "Tenant",
            "transit": {
                "class": "Application",
                "template": "generic",
                "transit_forward": {
                    "class": "Service_Forwarding",
                    "virtualAddresses": [
                            "0.0.0.0/0"
                    ],
                    "profileL4": {
                        "use": "route_friendly_fastl4"
                    },
                    "virtualPort": 0,
                    "forwardingType": "ip",
                    "layer4": "any",
                    "snat": "auto",
                    "translateServerAddress": false,
                    "translateServerPort": false,
                    "translateClientPort": "preserve-strict"
                },
                "route_friendly_fastl4": {
                    "class": "L4_Profile",
                    "idleTimeout": 300,
                    "looseClose": true,
                    "looseInitialization": true,
                    "resetOnTimeout": false
                },
                "transit_health_irule": {
                    "class": "iRule",
                    "iRule": "when HTTP_REQUEST {\n    HTTP::respond 200 content {\n        <html>\n        <head>\n        <title>Health Check</title>\n        </head>\n        <body>\n        System is online.\n        </body>\n        </html>\n        }\n}"
                },
                "transit_health": {
                    "class": "Service_HTTP",
                    "layer4": "tcp",
                    "iRules": [
                        "transit_health_irule"
                    ],
                    "profileHTTP": {
                        "bigip": "/Common/http"
                    },
                    "profileTCP": {
                        "bigip": "/Common/tcp"
                    },
                    "virtualAddresses": [
                        "10.90.7.11",
                        "10.90.7.12"
                    ],
                    "virtualPort": 34568,
                    "snat": "none"
                }
            }
        },
        "mgmt": {
            "class": "Tenant",
            "admin": {
                "class": "Application",
                "template": "generic",
                "rdp_pool": {
                    "members": [
                        {
                            "addressDiscovery": "static",
                            "servicePort": 3389,
                            "serverAddresses": [
                                "10.90.3.98"
                            ]
                        }
                    ],
                    "monitors": [
                        {
                            "bigip": "/Common/tcp_half_open"
                        }
                    ],
                    "class": "Pool"
                },
                "ssh_pool": {
                    "members": [
                        {
                            "addressDiscovery": "static",
                            "servicePort": 22,
                            "serverAddresses": [
                                "10.90.3.99"
                            ]
                        }
                    ],
                    "monitors": [
                        {
                            "bigip": "/Common/tcp_half_open"
                        }
                    ],
                    "class": "Pool"
                },
                "mgmt_health_irule": {
                    "class": "iRule",
                    "iRule": "when HTTP_REQUEST {\n    HTTP::respond 200 content {\n        <html>\n        <head>\n        <title>Health Check</title>\n        </head>\n        <body>\n        System is online.\n        </body>\n        </html>\n        }\n}"
                },
                "mgmt_http": {
                    "policyFirewallEnforced": {
                        "use": "/Common/Shared/sccaBaselineAFMPolicy"
                    },
                    "layer4": "tcp",
                    "iRules": [
                        "mgmt_health_irule"
                    ],
                    "securityLogProfiles": [
                        {
                            "use": "/Common/Shared/fwSecurityLogProfile"
                        }
                    ],
                    "translateServerAddress": true,
                    "translateServerPort": true,
                    "class": "Service_HTTP",
                    "profileDOS": {
                        "bigip": "/Common/dos"
                    },
                    "profileHTTP": {
                        "bigip": "/Common/http"
                    },
                    "profileTCP": {
                        "bigip": "/Common/tcp"
                    },
                    "virtualAddresses": [
                        "10.90.6.11",
                        "10.90.6.12"
                    ],
                    "virtualPort": 80,
                    "snat": "none"
                },
                "mgmt_rdp": {
                    "policyFirewallEnforced": {
                        "use": "/Common/Shared/sccaBaselineAFMPolicy"
                    },
                    "layer4": "tcp",
                    "pool": "rdp_pool",
                    "securityLogProfiles": [
                        {
                            "use": "/Common/Shared/fwSecurityLogProfile"
                        }
                    ],
                    "translateServerAddress": true,
                    "translateServerPort": true,
                    "class": "Service_TCP",
                    "profileTCP": {
                        "bigip": "/Common/tcp"
                    },
                    "virtualAddresses": [
                        "10.90.6.11",
                        "10.90.6.12"
                    ],
                    "virtualPort": 3389,
                    "snat": "auto"
                },
                "mgmt_ssh": {
                    "policyFirewallEnforced": {
                        "use": "/Common/Shared/sccaBaselineAFMPolicy"
                    },
                    "layer4": "tcp",
                    "pool": "ssh_pool",
                    "securityLogProfiles": [
                        {
                            "use": "/Common/Shared/fwSecurityLogProfile"
                        }
                    ],
                    "translateServerAddress": true,
                    "translateServerPort": true,
                    "class": "Service_TCP",
                    "profileDOS": {
                        "bigip": "/Common/dos"
                    },
                    "profileTCP": {
                        "bigip": "/Common/tcp"
                    },
                    "virtualAddresses": [
                        "10.90.6.11",
                        "10.90.6.12"
                    ],
                    "virtualPort": 22,
                    "snat": "auto"
                }
            }
        },    
        "example": {
            "class": "Tenant",
            "exampleApp": {
                "class": "Application",
                "template": "generic",
                "sccaBaselineExampleIPS": {
                    "policyFirewallEnforced": {
                        "use": "/Common/Shared/sccaBaselineAFMPolicy"
                    },
                    "layer4": "tcp",
                    "securityLogProfiles": [
                        {
                            "use": "/Common/Shared/fwSecurityLogProfile"
                        }
                    ],
                    "translateServerAddress": true,
                    "translateServerPort": false,
                    "class": "Service_TCP",
                    "profileDOS": {
                        "bigip": "/Common/dos"
                    },
                    "profileHTTP": {
                        "bigip": "/Common/http"
                    },
                    "profileTCP": {
                        "bigip": "/Common/tcp"
                    },
                    "virtualAddresses": [
                        "10.90.6.0/24"
                    ],
                    "virtualPort": 0,
                    "snat": "auto",
                    "pool": "sccaBaselineIPSPool"
                    
                },
                "sccaBaselineExampleHTTPS": {
                    "policyFirewallEnforced": {
                        "use": "/Common/Shared/sccaBaselineAFMPolicyHTTP"
                    },
                    "layer4": "tcp",
                    "securityLogProfiles": [
                        {
                            "use": "/Common/Shared/fwSecurityLogProfile"
                        }
                    ],
                    "translateServerAddress": true,
                    "translateServerPort": true,
                    "class": "Service_HTTPS",
                    "profileDOS": {
                        "bigip": "/Common/dos"
                    },
                    "profileHTTP": {
                        "bigip": "/Common/http"
                    },
                    "serverTLS": "/Common/Shared/sccaBaselineClientSSL",
                    "profileTCP": {
                        "bigip": "/Common/tcp"
                    },
                    "virtualAddresses": [
                        "10.90.6.0/24"
                    ],
                    "virtualPort": 443,
                    "snat": "auto",
                    "policyWAF": {
                        "use": "/Common/Shared/sccaBaselineWAFPolicy"
                    },
                    "pool": "sccaBaselineJuiceShop"
                },             
                "sccaBaselineExampleHTTP": {
                    "policyFirewallEnforced": {
                        "use": "/Common/Shared/sccaBaselineAFMPolicyHTTP"
                    },
                    "layer4": "tcp",
                    "securityLogProfiles": [
                        {
                            "use": "/Common/Shared/fwSecurityLogProfile"
                        }
                    ],
                    "translateServerAddress": true,
                    "translateServerPort": true,
                    "class": "Service_HTTP",
                    "profileDOS": {
                        "bigip": "/Common/dos"
                    },
                    "profileHTTP": {
                        "bigip": "/Common/http"
                    },
                    "profileTCP": {
                        "bigip": "/Common/tcp"
                    },
                    "virtualAddresses": [
                        "10.90.6.0/24"
                    ],
                    "virtualPort": 8080,
                    "snat": "auto",
                    "policyWAF": {
                        "use": "/Common/Shared/sccaBaselineWAFPolicy"
                    },
                    "pool": "sccaBaselinePimpMyLogs"
                },
                "sccaBaselineIPSPool": {
                    "members": [
                        {
                            "addressDiscovery": "static",
                            "servicePort": 443,
                            "serverAddresses": [
                                "10.90.10.101"
                            ]
                        }
                    ],
                    "class": "Pool"
                },
                "sccaBaselineJuiceShop": {
                    "monitors": [
                        {
                            "bigip": "/Common/http"
                        }
                    ],
                    "members": [
                        {
                            "addressDiscovery": "static",
                            "servicePort": 3000,
                            "serverAddresses": [
                                "10.90.10.101"
                            ]
                        }
                    ],
                    "class": "Pool"
                },
                "sccaBaselinePimpMyLogs": {
                    "monitors": [
                        {
                            "bigip": "/Common/http"
                        }
                    ],
                    "members": [
                        {
                            "addressDiscovery": "static",
                            "servicePort": 8080,
                            "serverAddresses": [
                                "10.90.10.101"
                            ]
                        }
                    ],
                    "class": "Pool"
                },
                "sccaBaselineDemoAppHttps": {
                    "monitors": [
                        {
                            "bigip": "/Common/https"
                        }
                    ],
                    "members": [
                        {
                            "addressDiscovery": "static",
                            "servicePort":443,
                            "serverAddresses": [
                                "10.90.10.101"
                            ]
                        }
                    ],
                    "class": "Pool"
                },
                "sccaBaselineDemoAppHttp": {
                    "monitors": [
                        {
                            "bigip": "/Common/http"
                        }
                    ],
                    "members": [
                        {
                            "addressDiscovery": "static",
                            "servicePort":80,
                            "serverAddresses": [
                                "10.90.10.101"
                            ]
                        }
                    ],
                    "class": "Pool"
                }
            }
    }
    }
}
```

2. Observe the following error response:
```
Wed, 16 Dec 2020 19:22:10 GMT - severe: [appsvcs] {"message":"Declaration failed: Thrift exception (probably ASM config server is not running): No more data to read.","level":"error"}

Wed, 16 Dec 2020 19:22:12 GMT - severe: [appsvcs] {"message":"Declaration failed: 01020036:3: The requested firewall virtual log profile (/Common/Shared/fwSecurityLogProfile) was not found.","level":"error"}

Wed, 16 Dec 2020 19:22:12 GMT - severe: [appsvcs] {"message":"Declaration failed: 01020036:3: The requested firewall virtual log profile (/Common/Shared/fwSecurityLogProfile) was not found.","level":"error"}
```
## first post
```
[xadmin@f5vm03:Active:In Sync] ~ # tmsh list auth partition
auth partition Common {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:22:49 GMT"
}
auth partition transit {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:21:39 GMT"
}
```
## second post
```
[xadmin@f5vm03:Active:In Sync] ~ # tmsh list auth partition
auth partition Common {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:22:49 GMT"
}
auth partition mgmt { }
auth partition transit {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:21:39 GMT"
}
```
## thrid post
```
[xadmin@f5vm03:Active:In Sync] ~ # tmsh list auth partition
auth partition Common {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:22:49 GMT"
}
auth partition mgmt { }
auth partition transit {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:21:39 GMT"
}
```
## forth post
```
[xadmin@f5vm03:Active:In Sync] ~ # tmsh list auth partition
auth partition Common {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:22:49 GMT"
}
auth partition mgmt { }
auth partition transit {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:21:39 GMT"
}
auth partition example {
    description "Updated by AS3 at Wed, 16 Dec 2020 19:24:29 GMT"
}
```
### Expected Behavior
a single post is rejected as failed, or the items in the example tenant wait for success, and are then created.

### Actual Behavior
a single post shows 200s for some tenants and not others.
continuing to post the declaration succeeds on the 4th attempt.

examples:
run-time-init: 
https://github.com/vinnie357/f5-azure-saca/blob/run-time-init/templates/runtime-init.sh.tpl
runtime sees the partial config as success, but this is open in a separate issue with that team.
bash with logging and loops:
https://github.com/vinnie357/f5-azure-saca/blob/run-time-init/templates/onboard.sh.tpl

**Comment by dstokesf5** [comment] 2021-03-12 17:57
I am unable to reproduce the behavior you are describing. I only get some IP conflicts on 10.90.10.101. However, after resolving those by using shareNodes, I was able to successfully POST the entire declaration multiple times.

Can you try updating to the latest AS3 version to see if that resolves your issue?

**Closed** 2021-05-21 16:35 UTC
Labels: bug, question
