### ISSUE TITLE
GSLB_Pool support for "use"

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-appsvcs-extension#588] opened 2022-04-04 16:32 UTC
### Is your feature request related to a problem? Please describe.
Environments that use a combined GTM + LTM with virtual server discovery create an issue with referencing a GSLB_Pool object that hasnt been created yet. When the WIP and the LTM objects are in the same declaration you cannot create a WIP as this isnt something that has been discovered yet.

### Describe the solution you'd like
Requesting that the schema be updated to allow a "use" item on the GSLB pool, in this case the pool would have the name of the virtual being created at the same time.

`                        "virtualServer": {
                            "use": "nginxCalalangNet_vs"
                        }`

schema only accepts strings:

`"virtualServer": "/nginxCalalangNet/nginx.calalang.net/nginxCalalangNet_vs",`

### Describe alternatives you've considered
There isnt an alternative, you have to re-post after the GSLB pool has been created, this requires the use of Patch or a "patch-like" pipeline that can be run so a whole declaration is sent again.

### Additional context
attached are my "tested" which produces the failure, as well as my common items and my desired declaration.

[tested-bigip-nginx-calalang-net-combined.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/8411491/tested-bigip-nginx-calalang-net-combined.txt)
[desired-bigip-nginx-calalang-net-combined.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/8411492/desired-bigip-nginx-calalang-net-combined.txt)
[bigip-gslb-common.txt](https://github.com/F5Networks/f5-appsvcs-extension/files/8411493/bigip-gslb-common.txt)

@mdditt2000

**Comment by dstokesf5** [comment] 2022-04-11 21:06
@jmcalalang Are you able to provide an example of the tmsh configuration you wish to achieve with this feature request?

**Comment by jmcalalang** [comment] 2022-04-11 21:16
I put it in here as an example, I don't think tmsh has a use (json pointer)?

**Comment by dstokesf5** [comment] 2022-04-11 21:20
Most of what AS3 does is generate tmsh configuration. In order to better understand your feature request, I am trying to figure out how that use-pointer would get translated into tmsh. I have been trying to guess at what that configuration might be, but I am getting nothing but errors so far.

**Comment by dstokesf5** [comment] 2022-04-12 15:41
It appears this is a duplicate of #578. Closing this issue.

**Closed by dstokesf5** 2022-04-12 15:41 UTC
Labels: enhancement, question

**Comment by seattlevine** [comment] 2022-08-24 20:27
We are fixing this now. However, the solution is not adding 'use' support to the `virtualServer`. Rather, as the gtm sub-system takes some time to discover ltm virtuals when `virtualServerDiscoveryMode` is enabled, we are adding a delay before creating any gtm pools that refer to an existing non-AS3 gtm server or refer to an AS3 gtm server that has `virtualServerDiscoveryMode` enabled.
