### ISSUE TITLE
Cannot upload iRule due to multiple 422 errors

### ISSUE THREAD

**Issue by thepowercoders** [F5Networks/f5-appsvcs-extension#693] opened 2023-02-09 23:17 UTC
### Environment
 * Application Services Version: AS3: 3.41.0
 * BIG-IP Version: VE 16.1.2

### Summary
Unable to successfully upload an iRule using AS3 which can be added with no issue via the GUI.

### Steps To Reproduce

First issue was that the iRule had a logging entry:
`if { $static::DEBUG } { log local0.debug "payload: <[TCP::payload]>" }`

This kept failing to upload with the error Declaration Cannot be Processed (422) and the following result:
`HTML Tag-like Content in the Request URL/Body`

I assumed this was because AS3 didn't like the "<" and ">" in the logging text within the iRule (even though this is not a HTML tag). I removed this and tried again... this time I got a different 422 error:
```
 01070151:3: Rule [/Common/Shared/irule-dccecos-ftps] error: /Common/Shared/irule-dccecos-ftps:17: error: [braces are required around the expression][when RULE_INIT {
```
now AS3 seems to want "[" and "]" braces around every `when <EVENT>` statement. I therefore added these and now I get this 422 error:
`"response": "the \\\"create\\\" command does not accept wildcard configuration identifiers",`

I've given up with ideas now as I don't even understand what this means.

### Expected Behavior
The iRule can be added manually via the GUI and it is syntax correct and accepted.

### Actual Behavior
I cannot get the iRule uploaded via AS3 which introduces another manual step in the automation-toolchain for me.

I'm happy to provide the iRule if needed, but don't want to paste it here due to end-client privacy reasons.

**Comment by antonywm** [comment] 2023-02-09 23:21
forgot to mention - I am trying to add the rule using base64 encoding as per below snippet: 
```
				"irule-test": {
					"class": "iRule",
					"remark": "test",
					"iRule": {
						"base64": "<base-64-string>"
					}
				},
```

**Comment by RobCupples** [comment] 2023-02-10 00:38
I took a look at your first issue.  By itself the BIGIP GUI wouldn't accept it until I tried wrapping it within a 'when CLIENT_DATA` block.  After base64 encoding it I was able to get it to work in a declaration.

```
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "controls": {
            "class": "Controls",
            "trace": true,
            "logLevel": "debug"
        },
        "Tenant": {
            "class": "Tenant",
            "A1": {
                "class": "Application",
                "irule-test": {
                    "class": "iRule",
                    "remark": "test",
                    "iRule": {
                        "base64": "d2hlbiBDTElFTlRfREFUQSB7CiAgaWYgeyAkc3RhdGljOjpERUJVRyB9IHsgbG9nIGxvY2FsMC5kZWJ1ZyAicGF5bG9hZDogPFtUQ1A6OnBheWxvYWRdPiIgfQp9"
                    }
                }
            }
        }
    }
}
```

We might need to see the specifics of your irule(s) to investigate further.
I expect either @mdditt2000 or @sunitharonan will be in contact to assist.

**Comment by heal01** [comment] 2023-02-21 08:14
Hi,
we are having the same problem uploading irules via Terraform and as3. This irule can be added via the gui but not via as3.

when HTTP_REQUEST {
    if { [whereis [IP::client_addr] country] eq "test" } {
        HTTP::respond 200 content "<!DOCTYPE html>\
            <html lang="en" xmlns="http://www.w3.org/1999/xhtml">\
            <head><meta charset="utf-8" />\
            <title></title>\
            </head>\
            <body>\
            </body>\
            </html>"
    }
}

Terraform apply change:
+ test2_irule                = {
                              + class = "iRule"
                              + iRule = {
                                  + base64 = "d2hlbiBIVFRQX1JFUVVFU1QgewogICAgaWYgeyBbd2hlcmVpcyBbSVA6OmNsaWVudF9hZGRyXSBjb3VudHJ5XSBlcSAidGVzdCIgfSB7CiAgICAgICAgSFRUUDo6cmVzcG9uZCAyMDAgY29udGVudCAiPCFET0NUWVBFIGh0bWw+XAogICAgICAgICAgICA8aHRtbCBsYW5nPSJlbiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiPlwKICAgICAgICAgICAgPGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiIC8+XAogICAgICAgICAgICA8dGl0bGU+PC90aXRsZT5cCiAgICAgICAgICAgIDwvaGVhZD5cCiAgICAgICAgICAgIDxib2R5PlwKICAgICAgICAgICAgPC9ib2R5PlwKICAgICAgICAgICAgPC9odG1sPiIKICAgIH0KfQo="


Terraform response after apply:
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

In restnoded log:
Tue, 21 Feb 2023 08:04:56 GMT - severe: [appsvcs] {"message":"Declaration failed: 01070151:3: Rule [/heal01_test_TFv2/heal01_test_TFv2_app/test2_irule] error: /heal01_test_TFv2/heal01_test_TFv2_app/test2_irule:5: error: [undefined procedure: <head><meta][<head><meta charset=\\\"utf-8\\\" />]\n/heal01_test_TFv2/heal01_test_TFv2_app/test2_irule:6: error: [undefined procedure: <title></title>][<title></title>]\n/heal01_test_TFv2/heal01_test_TFv2_app/test2_irule:7: error: [undefined procedure: </head>][</head>]\n/heal01_test_TFv2/heal01_test_TFv2_app/test2_irule:8: error: [undefined procedure: <body>][<body>]\n/heal01_test_TFv2/heal01_test_TFv2_app/test2_irule:9: error: [undefined procedure: </body>][</body>]\n/heal01_test_TFv2/heal01_test_TFv2_app/test2_irule:10: error: [undefined procedure: </html>\\\"][</html>\\\"]\n","level":"error"}
Tue, 21 Feb 2023 08:05:45 GMT - finest: socket 487 closed

**Comment by heal01** [comment] 2023-02-21 14:27
Hi,
we have the exact same problem when uploading some of our irules via terraform and as3. Let me know if I can help in any way.

**Comment by sunitharonan** [comment] 2023-02-22 18:54
Hi @antonywm, AUTOTOOL-3674 has been created for the same and added to our internal product backlog.

**Comment by mdditt2000** [comment] 2023-02-22 22:08
@antonywm please can you send me the irule automation_toolchain_pm@f5.com - would like to get this resolved in AS3-44

**Comment by antonywm** [comment] 2023-03-01 12:48
@mdditt2000 - I've sent this to internally to my SE. He will forward onto you.

**Comment by RobCupples** [comment] 2023-03-02 19:55
I was able to examine this irule.  I wanted to let you and anyone else following this issue to know right away that there are "<" and ">" symbols in a comment block and this is what is triggering the error.  If you remove these characters it works.  It also works if you replace them with &lt and &gt but either approach makes the comments harder to read.

**Comment by heal01** [comment] 2023-03-03 12:53
Hi @RobCupples doesn't look like it solved it for us. I replaced all < and > with §lt and §gt but I get the same error. I will send the iRule to the email address above.

**Comment by antonywm** [comment] 2023-03-03 16:49
@RobCupples - Check my original post .. I’d already found the issue with the < and > but this just caused another error

**Comment by RobCupples** [comment] 2023-03-07 22:56
I examined irules submitted from heal01 and antonywm and have not been able to reproduce this after removing or replacing any < or > in comments.  A declaration with the irule posted successfully.  I'm trying to think of any other information to ask that might help reproduce this. Are you posting the declaration directly with a tool such as Postman or indirectly with another tool such as Ansible or F5's FAST?

**Comment by heal01** [comment] 2023-03-08 07:16
@RobCupples we are using Terraform and as3, Terraform v1.3.9 and bigip v1.16.2

.tf file
"irule_name" = {
      irule = file("irules/irule_name.irule")
}
iRules = [
        { use = "irule_name" }
]

and in a template file
"iRules": ${jsonencode(vip.iRules)}

**Comment by RobCupples** [comment] 2023-03-09 17:41
I did find a KB article mentioning this error message can happen if an irule contains Unicode or UTF-8 characters.

https://my.f5.com/manage/s/article/K44543159

**Comment by heal01** [comment] 2023-03-10 09:18
Hi Rob,

Thanks. All the spaces is not in the original iRule must have been added when it was zipped. I can paste it in the web gui without any errors.
I got it to work when removing the strange characters you mentioned and I changed the HSL part of the irule shown below. I don’t know if that changes the behavior of it though?

I have to enclose the string in curly braces instead of “ otherwise I get this error

{"message":"Declaration failed: 01070151:3: Rule [/Common/Shared/generic-tool-sorry_page] error: /Common/Shared/generic-tool-sorry_page:378: error: [wrong # args][string map [list \\\"\\\\t</%22/t> \\\\t\\\</t/>" \\\"\\\\t-\\\\t\\\"]]\n","level":"error</%22/t-/t/%22%5d%5d/n%22,%22level%22:%22error>"}

From
HSL::send $hsl “[string map [list "\t \t" "\t-\t"]
    "<153>\t
        [info hostname]\t
        [IP::local_addr]\t
        [clock format [clock seconds] -format "%d/%m/%Y %H:%M:%S %z"]\t
        sorry_page\t
        /Common/generic-sorry-page\t
        [virtual name]\t
        [IP::remote_addr]\t
        [whereis [IP::client_addr] country]\t
        [HTTP::host]\t
        [HTTP::path]\t
        [LB::server pool]\t
        "]\n”

To
HSL::send $hsl {[string map [list "\t \t" "\t-\t"]
    "<153>\t
        [info hostname]\t
        [IP::local_addr]\t
        [clock format [clock seconds] -format "%d/%m/%Y %H:%M:%S %z"]\t
        sorry_page\t
        /Common/generic-sorry-page\t
        [virtual name]\t
        [IP::remote_addr]\t
        [whereis [IP::client_addr] country]\t
        [HTTP::host]\t
        [HTTP::path]\t
        [LB::server pool]\t
        "]\n}

Regards,

Henrik

From: Rob Cupples ***@***.***>
Date: Thursday, 9 March 2023 at 18:41
To: F5Networks/f5-appsvcs-extension ***@***.***>
Cc: Henrik Alm ***@***.***>, Comment ***@***.***>
Subject: Re: [F5Networks/f5-appsvcs-extension] Cannot upload iRule due to multiple 422 errors (Issue #693)

I did find a KB article mentioning this error message can happen if an irule contains Unicode or UTF-8 characters.

https://my.f5.com/manage/s/article/K44543159<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmy.f5.com%2Fmanage%2Fs%2Farticle%2FK44543159&data=05%7C01%7Chenrik.alm%40betssongroup.com%7C2e0fc18c01de4648cac008db20c58573%7Cc514bc364b3348d2bbb1a3c97d4bf41d%7C0%7C0%7C638139804942535580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1dJ4PPvUD%2FOrcRAmauYg2SKvD0yKbiYUjldlA7Wwpis%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FF5Networks%2Ff5-appsvcs-extension%2Fissues%2F693%23issuecomment-1462484988&data=05%7C01%7Chenrik.alm%40betssongroup.com%7C2e0fc18c01de4648cac008db20c58573%7Cc514bc364b3348d2bbb1a3c97d4bf41d%7C0%7C0%7C638139804942535580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8Jt00u%2B1VLCT4KCngZVKHIpqPMYAYubQpKz6L6u%2BCK8%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQPSDSIKQR2L5OOP7MJVXK3W3II4XANCNFSM6AAAAAAUXERKVE&data=05%7C01%7Chenrik.alm%40betssongroup.com%7C2e0fc18c01de4648cac008db20c58573%7Cc514bc364b3348d2bbb1a3c97d4bf41d%7C0%7C0%7C638139804942535580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xSoPygqD79w45E5Cj9Le95eGAdcfcBYcbZvICKAucHM%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by RobCupples** [comment] 2023-03-10 17:10
I was getting a similar error and discovered that it works if you put the entire HSL::send on a single line.  AS3 is mishandling the line continuations.  I will be creating an issue on this but the deadline has passed to get it into the next release.

I don't know if adding the braces changes the behavior.

**Comment by thepowercoders** [comment] 2023-04-13 22:46
Hi Rob - thanks for this you've cracked it! It is a problem with UTF-8 characters. I was using the well know site [https://www.base64encode.org](https://www.base64encode.org) to encode my iRule but this must have been converting certain characters incorrectly as the default option for "Destination Character Set" is to use UTF-8 (see below). When I changed this to ASCII, AS3 loaded the iRule perfectly without any issue.

![image](https://user-images.githubusercontent.com/32461620/231898793-3372e207-66cb-44bf-865b-ca1db9fba7b3.png)

**Closed** 2023-04-13 23:03 UTC
Labels: bug
