### ISSUE TITLE
iRules are stripped of leading comment lines and empty lines

### ISSUE THREAD

**Issue by j-zehnder** [F5Networks/f5-appsvcs-extension#518] opened 2021-09-30 19:27 UTC
### Environment
 * Application Services Version: 3.31.0
 * BIG-IP Version: BIG-IP 15.1.2.1 Build 0.0.10 Point Release 1

### Summary
When uploading iRules, leading comment lines are stripped and empty lines in the file are removed . This causes the as3 action "dry-run" to always report that changes are needed (never returns "no change").

### Steps To Reproduce
1. Submit the following declaration:
for the following iRule:
```tcl
# Leading Comment
when HTTP_RESPONSE_RELEASE priority 800 {
    # Check for any prior HTTP::redirect or HTTP::respond processing before continuing
    if {[HTTP::has_responded]} {return}


    # Remove Server Identifier headers after all prior events have processed right before the response is committed to the client.
    HTTP::header remove Server
}
```
```json
{
    "class": "AS3",
    "action": "deploy",
    "persist": false,
    "historyLimit": 2,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.31.0",
        "updateMode": "selective",
        "id": "Foo",
        "Foo": {
            "class": "Tenant",
            "app": {
                "class": "Application",
                "my_rule": {
                    "class": "iRule",
                    "iRule": { "base64": "IyBMZWFkaW5nIENvbW1lbnQNCndoZW4gSFRUUF9SRVNQT05TRV9SRUxFQVNFIHByaW9yaXR5IDgwMCB7DQogICAgIyBDaGVjayBmb3IgYW55IHByaW9yIEhUVFA6OnJlZGlyZWN0IG9yIEhUVFA6OnJlc3BvbmQgcHJvY2Vzc2luZyBiZWZvcmUgY29udGludWluZw0KICAgIGlmIHtbSFRUUDo6aGFzX3Jlc3BvbmRlZF19IHtyZXR1cm59DQoNCg0KICAgICMgUmVtb3ZlIFNlcnZlciBJZGVudGlmaWVyIGhlYWRlcnMgYWZ0ZXIgYWxsIHByaW9yIGV2ZW50cyBoYXZlIHByb2Nlc3NlZCByaWdodCBiZWZvcmUgdGhlIHJlc3BvbnNlIGlzIGNvbW1pdHRlZCB0byB0aGUgY2xpZW50Lg0KICAgIEhUVFA6OmhlYWRlciByZW1vdmUgU2VydmVyDQp9" }
                }
            }
        }
    }
}
```

subsequent calls may be made with `"action": "dry-run"`

2. Observe the following error response:
there is not an error message, see Actual Behavior

### Expected Behavior
the iRule should be loaded to the box exactly as it was encoded.

### Actual Behavior
The deployed iRule looks as follows:
```tcl
when HTTP_RESPONSE_RELEASE priority 800 {
    # Check for any prior HTTP::redirect or HTTP::respond processing before continuing
    if {[HTTP::has_responded]} {return}
    # Remove Server Identifier headers after all prior events have processed right before the response is committed to the client.
    HTTP::header remove Server
}  
```
note the lack of leading comment and empty lines

**Comment by j-zehnder** [comment] 2021-09-30 19:28
As an additional note, when there are multiple lines of leading comments, only the first is removed

**Comment by dstokesf5** [comment] 2021-09-30 20:29
Thank you for reporting this. However, it has already been reported. I am closing this issue as a duplicate of #252.

**Closed** 2021-10-04 18:30 UTC
Labels: bug, duplicate
