### ISSUE TITLE
BIG-IP Shared Objects/Address List

### ISSUE THREAD

**Issue by iluvpcs** [F5Networks/f5-appsvcs-extension#412] opened 2021-02-09 18:25 UTC
Searched and didn't see this in 3.25 reference schema

Feature request:
https://techdocs.f5.com/en-us/bigip-15-1-0/big-ip-ltm-virtual-servers-multiple-ip-port/virtual-server-multiple-addresses-service-ports-configuring/task-summary-vs-range-ip-addrs-ports/create-address-list-for-vs.html

### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Customer would like to use this feature to allow only certain users to access a virtual server

### Describe alternatives you've considered
an iRule or not use AS3

**Comment by dstokesf5** [comment] 2021-09-01 21:58
Closing this as a duplicate of #269. Please see that issue for more information on the TMOS bugs that prevent AS3 for adding this functionality.

**Closed by dstokesf5** 2021-09-01 21:58 UTC
Labels: enhancement, untriaged
