### ISSUE TITLE
Endpoint policy condition "httpUri" host is not accurate

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-appsvcs-extension#397] opened 2020-12-17 17:34 UTC
### Environment
 * 3.24.0
 * BIG-IP Version: 15.1

### Summary
When using an endpoint policy and using condition "httpUri" with "host" the LTM policy rule doesn't match because the LTM policy rule evaluation fails. 

### Steps To Reproduce

1. Submit the following declaration: (sorry if the declaration is broken, I took the default one and modified it a bit)

```json
{
    "schemaVersion": "3.24.0",
    "class": "ADC",
    "Tenant": {
        "class": "Tenant",
        "Application": {
            "template": "generic",
            "vip": {
                "class": "Service_HTTPS",
                "virtualAddresses": ["192.0.2.0"],
                "policyEndpoint": "test1"
            },
            "test1": {
                "class": "Endpoint_Policy",
                "rules": [
                    {
                        "name": "host_x.domain.com_path_bla_bla",
                        "conditions": [
                            {
                                "type": "httpUri",
                                "event": "request",
                                "host": {
                                    "operand": "equals",
                                    "values": [
                                        "x.domain.com"
                                    ]
                                }
                            },
                            {
                                "type": "httpUri",
                                "event": "request",
                                "path": {
                                    "operand": "starts-with",
                                    "values": [
                                        "/bla/bla"
                                    ]
                                }
                            }
                        ],
                        "actions": [
                            {
                                "type": "forward",
                                "select": {
                                    "pool": {
                                        "bigip": "/Common/pool"
                                    }
                                }
                            }
                        ]
                    }
              }
        }
    }
}
```

2. Observe the following error response:
The declaration is submitted successfully but the LTM policy matching is not accurate. When sending a request with name x.domain.com/bla/bla it is not evaluated as true (in the actual use case I have a default rule that is matched instead)

### Expected Behavior
The policy rule host_x.domain.com_path_bla_bla to match and the request to be forwarded

### Actual Behavior
The policy rule does not evaluate to true as the default rule hits instead. This is probably an F5 ltm policy issue but what should be implemented in AS3 is the possibility to match against "http host" as it is using the GUI.

Right now, as a work around we have to define the rule as "httpHeader" and specify "host" (this works) but httpUri host should work as well since it's documented.

If the LTM is broken and not fixable, I suggest that as3 changes the way "httpUri" host is parsed and instead of:

![image](https://user-images.githubusercontent.com/64788752/102521762-993abb80-4095-11eb-9623-8befe3ad07ee.png)

It should be configured as:

![image](https://user-images.githubusercontent.com/64788752/102521883-c4bda600-4095-11eb-993c-7554950ad69f.png)

Or make it possible to use "httpHost" instead of "httpUri".

Either way, with the current as3, it's not possible to make it end up as the second picture looks (I edited it manually in the GUI), which unfortunately makes this a clear flaw.

**Comment by dstokesf5** [comment] 2020-12-17 18:02
It looks like the http-host condition of ltm policies matches against the host header. Have you tried using the httpHeader type?
```json
                            {
                                "type": "httpHeader",
                                "event": "request",
                                "name": "Host",
                                "all": {
                                    "operand": "equals",
                                    "values": [
                                        "x.domain.com"
                                    ]
                                }
                            },
```

**Comment by oakh1** [comment] 2020-12-17 18:12
Yep, that's what I wrote as the workaround, that the only way to solve it is using "httpHeader" and then "host" (as in your example). The http-host condition of LTM policies matches against the host header, that's true and that's how it should work? :) 

If httpUri - host doesn't match against the host header (as it doesn't work), what does it match against? I don't have any port specified in the host either, so it's something fishy there.

The httpUri "host" should be removed or changed into "httpHost" "host" (as in the GUI).

**Comment by dstokesf5** [comment] 2020-12-17 18:21
The httpUri Endpoint_Policy condition is just a thin wrapper around the http-uri condition of ltm policy objects in tmsh. It appears AS3 is generating the expected tmsh output, but it is unclear to me why the http-uri ltm policy condition does not work as expected.

This ultimately appears to be an issue with ltm policy objects, and I recommend following up with F5 support on why those do not appear to be working as intended.

**Comment by oakh1** [comment] 2020-12-17 19:24
Earlier when we had discussions regarding bugs in the LTM policy evaluations, the response was that the LTM policies are so complicated that they don't want to make any changes to it. If that's still the case, would it be possible then, as an improvement for as3, to add the "httpHost" functionality to as3 (or simply changing httpUri host to httpHost host? As this exists in tmsh/GUI. So that you could configure (Written in yml now for ease):

type: httpHost
all: 
  operand: equals
  values:
    - myhost.domain.com:8443

or

type: httpHost
host: 
  operand: equals
  values:
    - myhost.domain.com
  
or

type: httpHost
port:
  operand: equals
  values:
    - 8443
    
Anyway, no rush and not urgent, as I know httpHeader and Host works (with starts with or w/e), but would make it more clean as sometimes the port is provided in the hostHeader, sometimes not, etc etc.

**Comment by dstokesf5** [comment] 2020-12-17 19:32
I am going to change this to a feature request to help AS3 users avoid TMSH pitfalls. Thank you for your feedback.

**Comment by dstokesf5** [comment] 2021-09-02 20:24
We have decided that providing a work around for TMOS bugs is not something we want to commit resources to at this time. It would be best to raise a ticket with F5 support to get those resolved directly. I am closing out this issue. Thank you for your feedback.

**Closed by dstokesf5** 2021-09-02 20:24 UTC
Labels: enhancement, untriaged
