### ISSUE TITLE
Node route domain when defaultRouteDomain changed

### ISSUE THREAD

**Issue by stanislaspiron** [F5Networks/f5-appsvcs-extension#499] opened 2021-08-27 13:01 UTC
### Environment
 * Application Services Version: 3.30.0
 * BIG-IP Version: 15.1

### Summary
When the defaultRouteDomain attribute is changed on a tenant, there are following behaviors:
  - When defaultRouteDomain is changed on a tenant, virtual address is changed to expected route domain, nodes are not
  - When the tenant is deleted and recreated with the new defaultRouteDomain value, virtual address is changed to expected route domain, nodes too
This declaration is not idempotent.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "MyTenant": {
        "MyApp": {
            "class": "Application",
            "enable": true,
            "MyPool": {
                "class": "Pool",
                "loadBalancingMode": "least-connections-member",
                "members": [
                    {
                        "enable": true,
                        "priorityGroup": 0,
                        "serverAddresses": [
                            "20.1.1.1"
                        ],
                        "servicePort": 80
                    }
                ],
                "minimumMonitors": 1,
                "monitors": [
                    {
                        "bigip": "/Common/tcp"
                    }
                ]
            },
            "MyVS": {
                "class": "Service_L4",
                "enable": true,
                "pool": "MyPool",
                "virtualAddresses": [
                    "10.1.1.1"
                ],
                "virtualPort": 80,
                "virtualType": "standard"
            }
        },
        "class": "Tenant",
        "defaultRouteDomain": 50,
        "enable": true
    },
    "class": "ADC",
    "schemaVersion": "3.18.0",
    "updateMode": "selective"
}
```

2. Observe the following error response:
```json
{
    "code": 200,
    "message": "success",
    "lineCount": 24,
    "host": "localhost",
    "tenant": "MyTenant",
    "runTime": 1570
}
```

3. Submit the following declaration (only defaultRouteDomain is changed between declarations)
```json
{
    "MyTenant": {
        "MyApp": {
            "class": "Application",
            "enable": true,
            "MyPool": {
                "class": "Pool",
                "loadBalancingMode": "least-connections-member",
                "members": [
                    {
                        "enable": true,
                        "priorityGroup": 0,
                        "serverAddresses": [
                            "20.1.1.1"
                        ],
                        "servicePort": 80
                    }
                ],
                "minimumMonitors": 1,
                "monitors": [
                    {
                        "bigip": "/Common/tcp"
                    }
                ]
            },
            "MyVS": {
                "class": "Service_L4",
                "enable": true,
                "pool": "MyPool",
                "virtualAddresses": [
                    "10.1.1.1"
                ],
                "virtualPort": 80,
                "virtualType": "standard"
            }
        },
        "class": "Tenant",
        "defaultRouteDomain": 5,
        "enable": true
    },
    "class": "ADC",
    "schemaVersion": "3.18.0",
    "updateMode": "selective"
}
```

4. Observe the following error response:
```json
{
    "code": 200,
    "message": "success",
    "lineCount": 21,
    "host": "localhost",
    "tenant": "MyTenant",
    "runTime": 1935
}
```

### Expected Behavior
Node 20.1.1.1 should change IP from 20.1.1.1%50 to 20.1.1.1%5

### Actual Behavior
Node 20.1.1.1 IP address is still 20.1.1.1%50

**Comment by dstokesf5** [comment] 2021-08-31 19:28
Closing as duplicate of #479. I have tested this use case with the changes made for #479, and the new behavior matches the expected behavior.

**Closed by dstokesf5** 2021-08-31 19:28 UTC
Labels: bug, untriaged
