### ISSUE TITLE
Unable to attach ASM / WAF policy to virtual server

### ISSUE THREAD

**Issue by lm-sig** [F5Networks/f5-appsvcs-extension#148] opened 2019-09-09 19:51 UTC
##### Do you already have an issue opened with F5 support?
No.

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.13.1-1.noarch.rpm
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3
  Build       0.0.6
  Edition     Final
  Date        Fri Aug  2 20:39:15 PDT 2019
```

##### SUMMARY

I am deploying an AS3 template to a F5 provisioned for LTM and ASM. I imported an existing ASM policy XML file into the F5 as '/Partition/MyPolicy_Test'. The template is deploying a virtual server pointing to the existing ASM policy. When I tried to deploy the first time the ASM policy was deleted and AS3 responded with "Unable to find ..." the policy. I re-imported the policy and ran a second time. Now the response is always:

```
01071726:3: Cannot delete policy '/Partition/MyPolicy_Test'. It is in use by ltm policy '/Partition/my_app/_WAF_vs_my_app'.
```

##### STEPS TO REPRODUCE

```
    {
        "class": "AS3",
        "action": "deploy",
        "persist": true,
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "test-declaration-0",
            "label": "Test Declaration 0",
            "remark": "Test Declaration for My Apps",
            "Partition": {
                "class": "Tenant",
                "MyApp1": {
                    "class": "Application",
                    "template": "generic",
                    "MyApp1_VIP": {
                        "class": "Service_HTTPS",
                        ...
                        "policyWAF": {
                            "bigip": "/Partition/MyPolicy_Test"
                        },
                        ...
                }
            }
        }
    }
```

##### EXPECTED RESULTS

A successful deployment with the policy attached to the virtual server.

##### ACTUAL RESULTS

```
01071726:3: Cannot delete policy '/Partition/MyPolicy_Test'. It is in use by ltm policy '/Partition/my_app/_WAF_vs_my_app'.
```

**Comment by lm-sig** [comment] 2019-09-18 21:11
Similar workaround to issue 141 can be done here, too.

Loading the WAF into /Common allows AS3 to deploy successfully and it attaches the policy correctly.

**Comment by Kupoman** [comment] 2019-09-18 21:16
To have the WAF policy in the same partition that AS3 is configuring, please use a WAF_Policy AS3 class as shown in this example: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/application-security.html#virtual-service-referencing-an-external-security-policy

**Comment by dstokesf5** [comment] 2019-09-18 21:18
To have the WAF policy in the same partition that AS3 is configuring, please use a WAF_Policy AS3 class as shown in this example: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/application-security.html#virtual-service-referencing-an-external-security-policy

**Comment by lm-sig** [comment] 2019-10-22 21:04
The WAF_Policy class only supports pointing to an external URL or on-disk XML file. I do not want to use either of those options.

**Comment by dstokesf5** [comment] 2019-10-22 21:09
What option do you want to use? If AS3 is not managing the WAF policy, then it cannot be in an AS3 managed partition without causing problems.

**Comment by lm-sig** [comment] 2019-10-22 22:23
I hear you. I'm not trying to be difficult.

* Will AS3 support accepting the XML inside it? I know the XML files can be large.
* Could the WAFs be placed into a path inside the partition that is protected from AS3? Example: /Partition/noas3/WAF-foo-bar

**Comment by dstokesf5** [comment] 2019-10-22 22:42
I think putting the XML (possibly base64 encoded) into the declaration would be a reasonable feature request. We already have something similar for certificates (see [this example](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/tls-encryption.html#using-multiple-ssl-tls-certificates-in-a-single-profile)).

Will that satisfy your use case?

**Comment by dstokesf5** [comment] 2019-10-22 22:50
I went ahead and created a feature request AUTOTOOL-861 in our internal product backlog for being able to put the XML policy text into the declaration instead of fetching it from a remote source.

**Comment by dstokesf5** [comment] 2021-02-10 17:07
Looks like we had a collision in our internal product backlog. This issue was addressed in AUTOTOOL-2055.

**Comment by dstokesf5** [comment] 2021-02-10 17:08
I see what happened now. #375 duplicated this issue.

**Comment by dstokesf5** [comment] 2021-02-10 18:47
Closing this issue as a duplicate of #375.

**Closed by dstokesf5** 2021-02-10 18:47 UTC
Labels: enhancement
