### ISSUE TITLE
waf policy deployment fails 

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-appsvcs-extension#217] opened 2020-01-23 21:30 UTC
### Environment
 * Application Services Version: 3.16
 * BIG-IP Version: 15.1 

### Summary
using AS3 to declare an application with a WAF policy using the 'declarative waf' json format. 
on the first declaration it works as expected, but if i change any value in the waf json it fails and i get an error:
fatal: [localhost -> localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.7"}, "changed": false, "msg": "Import policy failed. Messages: [fatal] Failed action: Imported and replaced policies have different encodings.\n"}

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "AS3",
    "action": "deploy",
    "declaration": {
    "schemaVersion": "3.16.0",
    "class": "ADC",
    "id": "autogen_5efe91cc-7832-4538-9710-b0db00fc3fcf",
    "{{ deploy_env }}": {
      "juiceshop_{{ deploy_env }}": {
        "web_pool": {
          "loadBalancingMode": "predictive-node",
          "monitors": [
            "http"
          ],
          "members": [
            {
              "serverAddresses": [
                "{{ backend_server_address }}"
              ],
              "servicePort": 8081
            }
          ],
          "class": "Pool"
        },
        "juiceshop_waf_policy_{{ deploy_env }}": {
          "url": "http://gitlab.lab/waf_labs/waf_cicd/raw/master/waf_policy.json?inline=false",
          "ignoreChanges": false,
          "class": "WAF_Policy"
        },
        "juiceshop_{{ deploy_env }}": {
          "class": "Service_HTTP",
          "virtualAddresses": [
            "{{virtual_server_address}}"
          ],
          "virtualPort": 80,
          "snat": "auto",
          "policyWAF": {
            "use": "juiceshop_waf_policy_{{ deploy_env }}"
          },
          "pool": "web_pool"
        },
        "template": "generic",
        "class": "Application"
      },
      "class": "Tenant"
    }
  }
}

```
the waf_policy json file 
```
{
  "policy": {
    "name": "AppPolicy01",
    "description": "security policy for juiceshop",
    "template": {
      "name": "owasptop10"
    },
    "enforcementMode": "blocking",
    "server-technologies": [
      {
        "serverTechnologyName": "MySQL"
      },
      {
        "serverTechnologyName": "Unix/Linux"
      }
    ],
    "signature-settings": {
      "signatureStaging": false
    }
  },
  "modifications": [
  ]
}
```

then change the json file, like 
````
{
  "policy": {
    "name": "AppPolicy01",
    "description": "security policy for juiceshop",
    "template": {
      "name": "owasptop10"
    },
    "enforcementMode": "blocking",
    "server-technologies": [
      {
        "serverTechnologyName": "MySQL"
      },
      {
        "serverTechnologyName": "Unix/Linux"
      }
    ],
    "signature-settings": {
      "signatureStaging": false
    }
  },
  "modifications": [
    {
      "entityChanges": {
        "type": "explicit"
      },
      "entity": {
        "name": "bak"
      },
      "entityKind": "tm:asm:policies:filetypes:filetypestate",
      "action": "delete",
      "description": "Delete Disallowed File Type"
    },
    {
      "entityChanges": {
        "allowedResponseCodes": [
          403
        ]
      },
      "entity": {},
      "entityKind": "tm:asm:policies:general:generalstate",
      "action": "update-append",
      "description": "Add 403 to Allowed Response Codes."
    }
  ]
}

````
### Expected Behavior
policy should be updated

### Actual Behavior
fatal: [localhost -> localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.7"}, "changed": false, "msg": "Import policy failed. Messages: [fatal] Failed action: Imported and replaced policies have different encodings.\n"}

**Comment by dstokesf5** [comment] 2020-01-24 23:01
When I try to load your first policy, I get the following error from ASM:
```
Unexpected Error: Import policy failed. Messages: [fatal] Policy Template 'owasptop10' not found
```

Do you have a simpler example with less dependencies?

**Comment by dstokesf5** [comment] 2020-01-24 23:05
I tried loading the same policy twice through the command line with:
```
tmsh load asm policy foo file /config/dwaf-simple.json overwrite
```

And I got the same error you did:
```
Unexpected Error: Import policy failed. Messages: [fatal] Failed action: Imported and replaced policies have different encodings.
```

This looks like a problem with the declarative WAF feature on BIG-IP and not AS3.

**Comment by yossi-r** [comment] 2020-01-24 23:08
hi,
can you try replacing owasptop10  with POLICY_TEMPLATE_RAPID_DEPLOYMENT ?
it's a template that exists on all images
thanks

**Comment by yossi-r** [comment] 2020-01-24 23:14
if you use the REST API it works perfectly,
see the following example:

function upload_file_to_bigip() {    export size=`stat -c %s $1`
export size_minus=`expr $size - 1`    export
range="0-${size_minus}/${size}"    echo $range    curl -H
"Content-Range: $range" --data-binary "@$1" -sku
${bigip_user}:${bigip_password}
https://${bigip_server}/mgmt/tm/asm/file-transfer/uploads/policy.json}waf_to_bigip()
{    echo "Upload Policy to BIG-IP"    upload_file_to_bigip
waf_policy.json    echo "Import Policy to BIG-IP"    curl -sku
${bigip_user}:${bigip_password} -X POST
https://${bigip_server}//mgmt/tm/asm/tasks/import-policy/
-d'{"filename":"policy.json","policy":{"fullPath":"/Common/'${waf_policy_name}'"}}'
   echo "Apply Policy"    curl -sku ${bigip_user}:${bigip_password} -X
POST https://${bigip_server}//mgmt/tm/asm/tasks/apply-policy/
-d'{"policy":{"fullPath":"/Common/'${waf_policy_name}'"}}'}

notice that $waf_policy_name should be the same as the one defined in
the declaration.

so AS3 can take the name from the json and run the same API's

Thanks

**Comment by dstokesf5** [comment] 2020-01-30 20:55
I have confirmed that this is a bug with the API for importing WAF policies that AS3 is relying on. Closing this issue since this will need to be fixed in that API, which is outside of AS3's scope.

**Closed by dstokesf5** 2020-01-30 20:55 UTC
Labels: bug, invalid
