### ISSUE TITLE
POST requests by application on AS3

### ISSUE THREAD

**Issue by VincentPicardEspalion** [F5Networks/f5-appsvcs-extension#543] opened 2022-01-07 16:01 UTC
### Is your feature request related to a problem? Please describe.
When updating a single application, all the tenant is updated and this causes  performance issues

### Describe the solution you'd like
Being able to post a single application update request like : 
https://{{ bigip }}/mgmt/shared/appsvcs/declare/{{ tenant }}/{{application}}

### Describe alternatives you've considered
None

### Additional context
In our context we have 4500 VS in a tenant and we cannot use AS3

**Comment by dstokesf5** [comment] 2022-01-07 16:29
Thank you for your feedback. I am closing this issue as a duplicate of #253.

**Closed by dstokesf5** 2022-01-07 16:29 UTC
Labels: enhancement, untriaged
