### ISSUE TITLE
Node route domain when shareNodes and defaultRouteDomain

### ISSUE THREAD

**Issue by stanislaspiron** [F5Networks/f5-appsvcs-extension#500] opened 2021-08-27 15:03 UTC
### Environment
 * Application Services Version: 3.30.0
 * BIG-IP Version: 15.1

### Summary
When the defaultRouteDomain attribute is different than 0, we have this difference in configuration:
  - when shareNodes is false, the node is created in tenant partition with expected route domain
  - when shareNodes is true, the node is created in Common partition without route domain (Common partition default route domain)

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "MyTenant": {
        "MyApp": {
            "class": "Application",
            "enable": true,
            "MyPool": {
                "class": "Pool",
                "loadBalancingMode": "least-connections-member",
                "members": [
                    {
                        "enable": true,
                        "priorityGroup": 0,
                        "serverAddresses": [
                            "20.1.1.1"
                        ],
                        "servicePort": 80,
                        "shareNodes": false
                    }
                ],
                "minimumMonitors": 1,
                "monitors": [
                    {
                        "bigip": "/Common/tcp"
                    }
                ]
            },
            "MyVS": {
                "class": "Service_L4",
                "enable": true,
                "pool": "MyPool",
                "virtualAddresses": [
                    "10.1.1.1"
                ],
                "virtualPort": 80,
                "virtualType": "standard"
            }
        },
        "class": "Tenant",
        "defaultRouteDomain": 50,
        "enable": true
    },
    "class": "ADC",
    "schemaVersion": "3.18.0",
    "updateMode": "selective"
}
```

2. Observe Node route domain in WebUI

3. Submit the following declaration (only defaultRouteDomain is changed between declarations)
```json
```json
{
    "MyTenant": {
        "MyApp": {
            "class": "Application",
            "enable": true,
            "MyPool": {
                "class": "Pool",
                "loadBalancingMode": "least-connections-member",
                "members": [
                    {
                        "enable": true,
                        "priorityGroup": 0,
                        "serverAddresses": [
                            "20.1.1.1"
                        ],
                        "servicePort": 80,
                        "shareNodes": true
                    }
                ],
                "minimumMonitors": 1,
                "monitors": [
                    {
                        "bigip": "/Common/tcp"
                    }
                ]
            },
            "MyVS": {
                "class": "Service_L4",
                "enable": true,
                "pool": "MyPool",
                "virtualAddresses": [
                    "10.1.1.1"
                ],
                "virtualPort": 80,
                "virtualType": "standard"
            }
        },
        "class": "Tenant",
        "defaultRouteDomain": 50,
        "enable": true
    },
    "class": "ADC",
    "schemaVersion": "3.18.0",
    "updateMode": "selective"
}
```

4. 2. Observe Node route domain in WebUI

### Expected Behavior
In Both configuration, the node should be in Tenant defaultRouteDomain. To prevent duplicate Nodes in different route domains, Nodes in Common partition must include route domain ID in name

### Actual Behavior
When shareNodes is true, Node is created in Common default route domain.

**Comment by dstokesf5** [comment] 2021-08-31 19:49
Closing as duplicate of #499

**Comment by stanislaspiron** [comment] 2021-08-31 20:18
Hi @dstokesf5 This is not the same issue as #499 

This enhancement is to create a node with shareNodes attribute with tenant route domain and not Common partition Route domain. 
#499 is to move node route domain when changing tenant route domain.

Stan

**Comment by dstokesf5** [comment] 2021-08-31 20:40
I apologize, I was going through these too quickly. I have reopened the issue.

**Comment by dstokesf5** [comment] 2021-08-31 20:42
Step 3 says to change the route domain, but it looks like both declarations are using the same route domain. Did you intend to have the second declaration to have a different value for defaultRouteDomain, or am I misunderstanding something?

**Comment by dstokesf5** [comment] 2021-08-31 20:49
I looked over the two declarations again and see that the shareNodes property is what changes.

I have tested this use case with the changes made for #479, and the new behavior matches the expected behavior. Closing as duplicate of #479.

**Closed by dstokesf5** 2021-08-31 20:49 UTC
Labels: bug, question
