### ISSUE TITLE
as3 3.26.0 fails to completely load

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-appsvcs-extension#440] opened 2021-03-26 01:23 UTC
### Environment
 * Application Services Version: 3.26
 * BIG-IP Version: 15.1.2.1

### Summary
AS3 fails to load

```
Fri, 26 Mar 2021 01:10:00 GMT - finest: [LoaderWorker] triggered at path:  /var/config/rest/iapps/f5-appsvcs/nodejs/restWorker.js
Fri, 26 Mar 2021 01:10:01 GMT - info: starting /shared/appsvcs
Fri, 26 Mar 2021 01:10:06 GMT - warning: [appsvcs] {"message":"AS3 version: 3.26.0","level":"warning"}
Fri, 26 Mar 2021 01:10:06 GMT - finest: socket 205 closed
Fri, 26 Mar 2021 01:10:11 GMT - severe: [appsvcs] {"message":"Failed to complete startup. Error: socket hang up\n    at createHangUpError (_http_client.js:331:15)\n    at Socket.socketOnEnd (_http_client.js:423:23)\n    at emitNone (events.js:111:20)\n    at Socket.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","level":"error"}
Fri, 26 Mar 2021 01:10:11 GMT - severe: [RestWorker] [RestWorker] worker failed to load state: [object Object]:shared/appsvcs

Fri, 26 Mar 2021 01:18:47 GMT - info: SIGTERM
```
requires restarting restnoded to workaround

**Comment by dstokesf5** [comment] 2021-04-12 16:45
If you encounter this issue regularly, you could you try capturing log output while the `logLevel` is set to `"debug"` in the controls object of your AS3 declaration? https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#adc-controls

AS3 has to make several HTTP requests as it is starting up, and the information currently provided makes it difficult to narrow down which request may be causing a problem.

**Comment by dstokesf5** [comment] 2021-05-21 16:38
Closing this issue as a duplicate of #450.

**Closed by dstokesf5** 2021-05-21 16:38 UTC
Labels: bug, question
