### ISSUE TITLE
Invalid iRule definition return success when expecting error

### ISSUE THREAD

**Issue by joseph-9924** [F5Networks/f5-appsvcs-extension#536] opened 2021-12-10 21:56 UTC
### Environment
 * Application Services Version: 3.31.0
 * BIG-IP Version: 13.1.4.1

### Summary
When creating a  tenant containing an iRule that has an invalid definition "INVALID IRULE DEFINITION TEXT",  the declaration is accepted and we end up with 4 distinct empty iRules in /Common  bearing the name of each words in the definition.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "AS3",
    "action": "deploy",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "label": "AS3 Declaration",
        "TEST-CREATE-AS3.LAB.ACME.COM": {
            "class": "Tenant",
            "APP": {
                "class": "Application",
                "IRULE_01": {
                    "class": "iRule",
                    "iRule": {
                        "base64": "SU5WQUxJRCBJUlVMRSBERUZJTklUSU9OIFRFWFQ="
                    }
                }
            }
        }
    }
}
```

2. Observe the following success response (expecting an error):
```json
{
    "results": [
        {
            "code": 200,
            "message": "success",
            "lineCount": 28,
            "host": "localhost",
            "tenant": "TEST-CREATE-AS3.LAB.ACME.COM",
            "runTime": 1484
        }
    ],
    "declaration": {
        "TEST-CREATE-AS3.LAB.ACME.COM": {
            "class": "Tenant",
            "APP": {
                "class": "Application",
                "IRULE_01": {
                    "class": "iRule",
                    "iRule": {
                        "base64": "SU5WQUxJRCBJUlVMRSBERUZJTklUSU9OIFRFWFQ="
                    }
                }
            }
        },
        "class": "ADC",
        "schemaVersion": "3.0.0",
        "label": "AS3 Declaration",
        "id": "autogen_7211394a-4f5f-409d-98cb-0ba3bc1fdf01",
        "updateMode": "selective",
        "controls": {
            "archiveTimestamp": "2021-12-10T20:35:39.236Z"
        }
    }
}
```

### Expected Behavior
We would expect the declaration to fail on the basis that the iRule is invalid

### Actual Behavior
The declaration is accepted and we end up with 4 distinct empty iRules in /Common  bearing the name of each words in my definition.

![image](https://user-images.githubusercontent.com/95051215/145644894-e39fea13-4013-4a38-9ec8-c4a5e11eabf6.png)

**Comment by dstokesf5** [comment] 2022-01-07 19:54
Thank you for your feedback. I have confirmed this issue and added it to our internal product backlog as AUTOTOOL-2922.

**Comment by dstokesf5** [comment] 2022-01-07 19:57
Thank you for your feedback. I have confirmed the bug and added it to our internal product backlog as AUTOTOOL-2924.

I also confirmed that this error still occurs when using base64 encoding.

**Comment by sunitharonan** [comment] 2022-11-28 18:54
Thank you @joseph-9924 for reachign out. In order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com.

**Comment by dstokesf5** [comment] 2024-01-09 17:27
Unfortunately, it looks like BIG-IP is not properly notifying AS3 that the iRule is invalid when we upload it as part of a cli script. Without BIG-IP telling AS3 there is a problem, there is no way for AS3 to report those problem. Since this is a BIG-IP limitation, I am closing this issue as `wontfix`.

**Closed by dstokesf5** 2024-01-09 17:27 UTC
Labels: bug
