### ISSUE TITLE
RFE: Support for External monitors in GSLB

### ISSUE THREAD

**Issue by euphario** [F5Networks/f5-appsvcs-extension#437] opened 2021-03-24 16:34 UTC
### Is your feature request related to a problem? Please describe.
AS3 does not currently support external monitors, we would like it added for GSLB in particular.

### Describe the solution you'd like
Ideally it should be possible to install the scripts in /config/monitors, and reference the scripts in AS3. Our BIG-IP builds have the scripts pre-install so that is not the most important part. Been able to create external monitor and reference installed scripts would be sufficient for our needs.

### Describe alternatives you've considered
BIG-IP is built with the external monitor scripts installed.
We use the bash REST API endpoint to execute a TMSH command to create the external monitor. We do not currently use AS3 to configure our GTMs, this is a blocking point.

### Additional context

Something like this;

```json
{
  "class": "GSLB_Monitor_External",
  "run": {"bigip": "my_external_script"},
  "timeout": 15,
  "interval": 5,
  "arguments": "",
  "variables": [{"name1": "value1"},{"name2": "value2"}]
}
```

**Comment by dstokesf5** [comment] 2021-08-31 17:25
Closing as duplicate of #259.

**Closed by dstokesf5** 2021-08-31 17:25 UTC
Labels: enhancement, untriaged
