### ISSUE TITLE
Service discovery ID is incorrect when new ID is a substring of previously existing ID

### ISSUE THREAD

**Issue by manuwelakanade-GSLAB** [F5Networks/f5-appsvcs-extension#244] opened 2020-03-27 10:40 UTC
Observed this issue while testing F5 ACI ServiceCenter

## Environment
 * Application Services Version: 3.17.1
 * BIG-IP Version: 15.1.0

### Summary
If AS3 Service Discovery has an endpoint {"ip":"12.14.1.123","id":"/Partition1/12.14.1.123"} and if a new endpoint is posted to the endpoint of the type {"ip":"12.14.1.12","id":"12.14.1.12"} where the ID is a substring of the 1st endpoint's ID, then the service discovery endpoint shows the new node with a wrong ID: {"id":"/Partition1/12.14.1.123","ip":"12.14.1.12"}

### Steps To Reproduce
1. POST to https://BIG_IP/mgmt/shared/service-discovery/task/\~Partition1\~Application1\~svc_pool
[{"ip":"12.14.1.123","id":"12.14.1.123"}]
2. GET https://BIG_IP/mgmt/shared/service-discovery/task/\~Partition1\~Application1\~svc_pool
returns 
[{"ip":"12.14.1.123","id":"/Partition1/12.14.1.123"}]
So AS3 Service discovery changes the ID of this node by prepending partition
3. Add one more endpoint to above list and POST to service discovery endpoint
[{"ip":"12.14.1.123","id":"/Partition1/12.14.1.123"},  {"ip":"12.14.1.12","id":"12.14.1.12"}]
Note: Please ensure that the new node has IP and ID as substrings of 1st node
4. GET https://BIG_IP/mgmt/shared/service-discovery/task/\~Partition1\~Application1\~svc_pool returns:
[{"ip":"12.14.1.123","id":"/Partition1/12.14.1.123"},  {"ip":"12.14.1.12","id":"/Partition1/12.14.1.123"}]

### Expected Behavior
1. From point 4 both the nodes should not have same ID and should have different IDs. 
2. If POST again to the service discovery endpoint to remove the 12.14.1.12 endpoint by POSTing the endpoint list [{"ip":"12.14.1.123","id":"/Partition1/12.14.1.123"}], it removes the 12.14.1.12 from pool, but does not delete the node from BIG-IP even though the node is not a part of any other pool

### Actual Behavior
1. In point 4, the GET should return correct ID for both nodes so that 
GET https://BIG_IP/mgmt/shared/service-discovery/task/\~Partition1\~Application1\~svc_pool returns:
[{"ip":"12.14.1.123","id":"/Partition1/12.14.1.123"},  {"ip":"12.14.1.12","id":"/Partition1/12.14.1.12"}]
2. Removing 2nd node (which has wrong ID) from the POST should remove the pool member from the pool and should also delete the node from the BIG-IP, because it works for other nodes which don't have this wrong ID problem.

**Comment by kedargslab** [comment] 2020-03-28 04:41
Found during testing integration with F5 ACI ServiceCenter

**Comment by dstokesf5** [comment] 2020-04-13 19:58
Unfortunately, in this case, the Service Discovery worker appears to be working as intended. In order to make node management easier, it was decided early on in the development of the Service Discovery worker that IP conflicts should be resolved by re-using nodes when possible instead of raising an error.

Do see where this can be problematic for your use case. However, changing this now will result in a change in behavior which could be considered API breaking.

**Closed** 2021-05-21 16:19 UTC
Labels: bug, invalid
